export interface Product {
  slug: string;
  name: string;
  group: 'indie' | 'ai-engine' | 'product-intel' | 'self-evolution' | 'enterprise' | 'integrations';
  groupLabel: string;
  lightGroupLabel: string;
  status: 'LIVE' | 'LAUNCHING' | 'PLANNED' | 'BUILT';
  url?: string;
  stack: string[];
  metric: string;
  lightMetric: string;
  tagline: string;
  lightTagline: string;
  // SEO page content
  title: string;
  description: string;
  body: string;
  lightBody: string;
  howItWorks: string;
  lightHowItWorks: string;
  related: string[]; // slugs
}

export const products: Product[] = [
  // ═══════════════════════════════════════
  // INDIE PRODUCTS
  // ═══════════════════════════════════════
  {
    slug: 'coffeebot',
    name: 'CoffeeBot',
    group: 'indie',
    groupLabel: 'Indie Products',
    lightGroupLabel: 'Indie Products',
    status: 'LIVE',
    url: 'https://coffeebot.app',
    stack: ['Astro', 'Groq', 'Tailwind', '100+ profiles', 'quiz'],
    metric: '82 coffee profiles generated',
    lightMetric: '82 recommendations, 100+ varieties',
    tagline: 'AI coffee quiz',
    lightTagline: 'AI picks coffee based on taste preferences',
    title: 'CoffeeBot — AI Coffee Quiz',
    description: 'AI-powered coffee recommendation quiz. 8 questions, 100+ varieties, personalized match. Built with Astro, Groq, Tailwind.',
    body: 'CoffeeBot — AI-квиз, который подбирает кофе по вкусовым предпочтениям. 8 вопросов о крепости, кислотности, способе приготовления, бюджете — и AI рекомендует конкретный сорт из базы в 100+ позиций.\n\nПод капотом: структурированный промпт на Groq (Llama 3.3), который анализирует комбинацию ответов и матчит с профилями кофе. Генерация рекомендации — менее 2 секунд. Монетизация через партнёрские программы кофейных брендов.\n\nТехнически: статический Astro-сайт на Cloudflare Pages (бесплатный хостинг), Groq API для инференса (бесплатный тир), Tailwind CSS. Нулевая стоимость инфраструктуры.',
    lightBody: 'CoffeeBot — онлайн-квиз, который подбирает кофе под ваш вкус. Пользователь отвечает на 8 вопросов — крепкость, кислотность, способ приготовления, бюджет. AI анализирует ответы и рекомендует конкретный сорт из базы в 100+ позиций.\n\nРекомендация генерируется за 2 секунды. Монетизация — партнёрские программы кофейных брендов. 82 уникальных профиля сгенерировано за первую неделю.',
    howItWorks: 'User input (8 questions) → structured prompt → Groq inference (Llama 3.3, <2s) → match against 100+ coffee profiles → personalized recommendation. Zero infrastructure cost: Astro SSG + Cloudflare Pages + Groq free tier.',
    lightHowItWorks: 'Пользователь отвечает на 8 вопросов → AI анализирует предпочтения → подбирает кофе из 100+ сортов → персональная рекомендация за 2 секунды.',
    related: ['tool-sites', 'diycalc', 'fitcalc'],
  },
  {
    slug: 'inkcloak',
    name: 'InkCloak',
    group: 'indie',
    groupLabel: 'Indie Products',
    lightGroupLabel: 'Indie Products',
    status: 'LAUNCHING',
    url: 'https://inkcloak.com',
    stack: ['Next.js', 'DeBERTa', 'LoRA fine-tune', 'RunPod GPU', 'AUROC 0.9948', 'CUDA'],
    metric: 'AUROC 0.9948 detection accuracy',
    lightMetric: '99.5% accuracy, GPT/Claude/Gemini',
    tagline: 'AI text detector + humanizer',
    lightTagline: 'Detects AI text with 99.5% accuracy',
    title: 'InkCloak — AI Text Detector & Humanizer',
    description: 'Fine-tuned DeBERTa detector (AUROC 0.9948) + adversarial paraphrasing humanizer. LoRA fine-tune, RunPod GPU inference, Next.js frontend.',
    body: 'InkCloak — платформа для определения AI-сгенерированного текста и его гуманизации. Два компонента:\n\n**Детектор** — fine-tuned DeBERTa-v3-large через LoRA. Обучен на RAID benchmark dataset. AUROC 0.9948 на 10K тестовых текстов. Определяет тексты GPT-4, Claude, Gemini, Llama и других моделей.\n\n**Гуманизатор** — adversarial paraphrasing engine. Генерирует варианты текста и выбирает тот, который проходит детектор. Не просто синонимы — переструктурирование на уровне предложений.\n\nТренировка: RunPod A4000, $0.15 за запуск. Инференс: RunPod Serverless, ~$0.002 за запрос. Zero-log privacy, AES-256 encryption.',
    lightBody: 'InkCloak определяет, написан ли текст искусственным интеллектом. Точность — 99.5% (AUROC 0.9948). Работает с текстами GPT-4, Claude, Gemini и других моделей.\n\nВторой компонент — гуманизатор: переписывает AI-текст так, чтобы он читался естественно. Не замена слов на синонимы, а переструктурирование на уровне предложений.\n\nСобственная нейросеть, обученная на специализированном датасете. Стоимость обучения — $0.15 за запуск.',
    howItWorks: 'Text input → DeBERTa-v3-large (LoRA fine-tuned, AUROC 0.9948) → probability score. Humanizer: adversarial paraphrasing → generate variants → select one that passes detector. GPU inference on RunPod Serverless.',
    lightHowItWorks: 'Загрузите текст → нейросеть анализирует паттерны → вероятность AI-генерации. Гуманизатор: переписывает текст так, чтобы он читался естественно.',
    related: ['scrutly', 'aicpo-platform', 'knowledge-graph'],
  },
  {
    slug: 'scrutly',
    name: 'Scrutly',
    group: 'indie',
    groupLabel: 'Indie Products',
    lightGroupLabel: 'Indie Products',
    status: 'PLANNED',
    url: 'https://scrutly.ai',
    stack: ['Astro', 'DeBERTa', 'free'],
    metric: '',
    lightMetric: '',
    tagline: 'Free AI text detector',
    lightTagline: 'Free AI text check, no registration',
    title: 'Scrutly — Free AI Text Detector',
    description: 'Free AI text detection. Same DeBERTa model as InkCloak, no registration required. Fast, simple, accurate.',
    body: 'Scrutly — бесплатный детектор AI-текста. Та же модель DeBERTa, что и в InkCloak, но без гуманизации и без регистрации.\n\nЦелевая аудитория: преподаватели, редакторы, рецензенты — те, кому нужно быстро проверить текст. Вставил → получил результат → закрыл вкладку.\n\nМонетизация: freemium-воронка в InkCloak. Scrutly показывает что текст AI-сгенерирован, InkCloak предлагает его гуманизировать.',
    lightBody: 'Бесплатная проверка текста на AI. Без регистрации, результат за секунды. Для преподавателей, редакторов, рецензентов.\n\nТа же нейросеть, что и в InkCloak (AUROC 0.9948), но только детекция — без гуманизации.',
    howItWorks: 'Paste text → DeBERTa inference → AI probability score. No auth, no limits, no tracking.',
    lightHowItWorks: 'Вставьте текст → мгновенный результат: вероятность AI-генерации.',
    related: ['inkcloak', 'coffeebot', 'tool-sites'],
  },
  {
    slug: 'tool-sites',
    name: 'Tool Sites',
    group: 'indie',
    groupLabel: 'Indie Products',
    lightGroupLabel: 'Indie Products',
    status: 'LIVE',
    stack: ['Astro', 'MDX', 'programmatic SEO', '5 domains', '199 pages'],
    metric: '199 pages across 5 domains',
    lightMetric: '199 pages, 5 sites',
    tagline: '199 SEO pages across 5 domains',
    lightTagline: '199 niche tools for SEO traffic',
    title: 'Tool Sites — 199 Programmatic SEO Pages',
    description: '199 niche calculator and tool pages across 5 domains. Programmatic SEO with Astro, MDX, Cloudflare Pages. AI-generated content with manual editing.',
    body: 'Tool Sites — 5 нишевых сайтов с калькуляторами и инструментами. 199 страниц, каждая оптимизирована под конкретный поисковый запрос.\n\nПрограмматический SEO: один шаблон + структурированные данные = сотни уникальных страниц. Контент сгенерирован AI, но каждая страница вычитана и отредактирована вручную.\n\nСтек: Astro + MDX (статическая генерация), Cloudflare Pages (бесплатный хостинг). Время генерации одной страницы — 5 минут (AI пишет, человек проверяет).\n\nСайты: DIYCalc (стройматериалы), FitCalc (фитнес), и ещё 3 нишевых домена.',
    lightBody: '199 страниц с онлайн-калькуляторами и инструментами на 5 доменах. Программатический SEO: один шаблон генерирует сотни уникальных страниц под конкретные поисковые запросы.\n\nAI генерирует контент, человек проверяет качество. Бесплатный хостинг на Cloudflare Pages.',
    howItWorks: 'Template + structured data → Astro MDX → 199 unique pages. AI generates content → manual review → deploy to Cloudflare Pages. Zero hosting cost.',
    lightHowItWorks: 'Шаблон + данные → AI генерирует контент → ручная проверка → 199 уникальных страниц на 5 доменах.',
    related: ['diycalc', 'fitcalc', 'coffeebot'],
  },
  {
    slug: 'openclaw-finance',
    name: 'OpenClaw Finance',
    group: 'indie',
    groupLabel: 'Indie Products',
    lightGroupLabel: 'Indie Products',
    status: 'BUILT',
    stack: ['Python', 'DeepSeek R1', 'Docker', '5 agents', 'multi-agent'],
    metric: '5 agents, deployed on 2 machines',
    lightMetric: '5 agents, automated reports',
    tagline: 'AI agent factory for financial analytics',
    lightTagline: 'AI agents for financial analytics and consolidation',
    title: 'OpenClaw Finance — Multi-Agent Financial Analytics',
    description: '5 specialized AI agents for financial analysis, forecasting, portfolio management, risk assessment, and reporting. DeepSeek R1, Docker, multi-agent architecture.',
    body: 'OpenClaw Finance — фабрика AI-агентов для финансовой аналитики и консолидации. 5 специализированных агентов:\n\n1. **Analyst** — анализ финансовой отчётности (P&L, баланс, cash flow)\n2. **Forecaster** — прогнозирование на основе исторических данных\n3. **Portfolio** — формирование и ребалансировка портфеля\n4. **Risk** — оценка рисков и стресс-тестирование\n5. **Reporter** — генерация отчётов в структурированном формате\n\nКаждый агент имеет свой системный промпт, инструментарий и зону ответственности. DeepSeek R1-0528 обеспечивает качество reasoning на уровне GPT-4 при нулевой стоимости API.\n\nАрхитектура: multi-agent orchestration через Python, Docker-контейнеры для изоляции, SQLite для хранения.',
    lightBody: 'Пять AI-агентов для финансовой аналитики и консолидации: анализ отчётности, прогнозирование, управление портфелем, оценка рисков, генерация отчётов.\n\nКаждый агент специализируется на своей задаче. Модель DeepSeek R1 обеспечивает качество анализа на уровне GPT-4.',
    howItWorks: 'Task → orchestrator routes to specialized agent → DeepSeek R1 reasoning → structured output. 5 agents: Analyst, Forecaster, Portfolio, Risk, Reporter. Docker isolation, SQLite storage.',
    lightHowItWorks: 'Задача → оркестратор выбирает агента → AI анализирует → структурированный отчёт.',
    related: ['aicpo-platform', 'autonomous-llm-runtime', 'knowledge-graph'],
  },
  {
    slug: 'rackcloud',
    name: 'RackCloud',
    group: 'indie',
    groupLabel: 'Indie Products',
    lightGroupLabel: 'Indie Products',
    status: 'BUILT',
    stack: ['Claude Opus', 'Proxmox', '400+ servers', '17 services', '10 racks'],
    metric: '17 IaaS services, 400+ servers, 10 racks',
    lightMetric: '400+ servers, 17 services',
    tagline: 'Cloud platform architecture for 400+ servers',
    lightTagline: 'Cloud platform project for 400+ servers',
    title: 'RackCloud — IaaS Cloud Platform Architecture',
    description: 'Full IaaS provider architecture: 400+ bare-metal servers, 17 services, billing, dashboard. Designed with Claude Opus, Proxmox, Python.',
    body: 'RackCloud — проект архитектуры IaaS-провайдера с нуля. 400+ bare-metal серверов, 17 сервисов, полный стек от compute до billing.\n\n**17 сервисов:** compute (VM/containers), block storage, object storage, networking (VPC, load balancers, firewalls), DNS, CDN, monitoring, logging, IAM, billing, dashboard, API gateway, backup, database-as-a-service, Kubernetes-as-a-service, serverless, marketplace.\n\n**Инфраструктура:** 10 стоек, сетевая топология, план масштабирования, disaster recovery, roadmap на 12 месяцев.\n\nСпроектировано совместно с Claude Opus. Полная документация за 4 дня. Альтернатива Hetzner/DigitalOcean для локального рынка.',
    lightBody: 'Архитектура облачного провайдера: 400+ серверов, 17 сервисов (compute, storage, networking, billing, dashboard). Спроектировано за 4 дня с помощью AI.\n\nПолная документация: от сетевой топологии до ценообразования и roadmap.',
    howItWorks: 'Requirements → Claude Opus architecture design → 17 service specifications → network topology → pricing model → 12-month roadmap. Full documentation in 4 days.',
    lightHowItWorks: 'Требования → AI проектирует архитектуру → 17 спецификаций сервисов → документация за 4 дня.',
    related: ['aicpo-platform', 'system-health', 'product-health-monitor'],
  },
  {
    slug: 'diycalc',
    name: 'DIYCalc',
    group: 'indie',
    groupLabel: 'Indie Products',
    lightGroupLabel: 'Indie Products',
    status: 'LIVE',
    url: 'https://diycalc.co',
    stack: ['Astro', 'MDX', 'programmatic SEO', '30+ calculators'],
    metric: '30+ calculators',
    lightMetric: '30+ calculators',
    tagline: 'Construction material calculators',
    lightTagline: 'Construction material calculators',
    title: 'DIYCalc — Construction Material Calculators',
    description: '30+ free construction material calculators: concrete, tiles, paint, drywall. Quantity and cost calculation. Programmatic SEO with Astro.',
    body: 'DIYCalc — 30+ бесплатных калькуляторов стройматериалов. Бетон, плитка, краска, гипсокартон, утеплитель, кирпич, ламинат, обои.\n\nКаждый калькулятор считает количество материала и стоимость. SEO-оптимизация под запросы типа "сколько бетона нужно на фундамент", "расчёт плитки для ванной".\n\nПрограмматический SEO: один шаблон Astro + MDX, структурированные данные по каждому материалу = уникальная страница с формулами и рекомендациями.',
    lightBody: '30+ бесплатных калькуляторов: сколько бетона на фундамент, сколько плитки на ванную, сколько краски на комнату. Расчёт количества и стоимости материалов.',
    howItWorks: 'User inputs dimensions → formula calculation → material quantity + cost estimate. Astro MDX, programmatic SEO, Cloudflare Pages.',
    lightHowItWorks: 'Введите размеры → расчёт количества материала → стоимость.',
    related: ['fitcalc', 'tool-sites', 'coffeebot'],
  },
  {
    slug: 'fitcalc',
    name: 'FitCalc',
    group: 'indie',
    groupLabel: 'Indie Products',
    lightGroupLabel: 'Indie Products',
    status: 'LIVE',
    url: 'https://fitcalc.co',
    stack: ['Astro', 'MDX', 'programmatic SEO', '40+ calculators'],
    metric: '40+ calculators',
    lightMetric: '40+ calculators',
    tagline: 'Health & fitness calculators',
    lightTagline: 'Health & fitness calculators',
    title: 'FitCalc — Health & Fitness Calculators',
    description: '40+ free fitness calculators: TDEE, BMI, body fat, macros, calories. Scientific formulas with personalized recommendations.',
    body: 'FitCalc — 40+ калькуляторов здоровья и фитнеса. TDEE, ИМТ, процент жира, макросы, калории, водный баланс, пульсовые зоны.\n\nНаучные формулы: Mifflin-St Jeor, Harris-Benedict, Katch-McArdle. Персональные рекомендации на основе введённых данных.\n\nSEO-оптимизация под запросы "калькулятор калорий", "расчёт TDEE", "ИМТ калькулятор". Программатический SEO на Astro + MDX.',
    lightBody: '40+ калькуляторов: калории, ИМТ, процент жира, макросы, водный баланс. Научные формулы с персональными рекомендациями.',
    howItWorks: 'User inputs (age, weight, height, activity) → scientific formula (Mifflin-St Jeor / Harris-Benedict) → personalized result + recommendations.',
    lightHowItWorks: 'Введите параметры → научная формула → персональный результат с рекомендациями.',
    related: ['diycalc', 'tool-sites', 'coffeebot'],
  },

  // ═══════════════════════════════════════
  // CORPORATE / AI ENGINE
  // ═══════════════════════════════════════
  {
    slug: 'autonomous-llm-runtime',
    name: 'Autonomous LLM Runtime',
    group: 'ai-engine',
    groupLabel: 'Corporate / AI Engine',
    lightGroupLabel: 'Corporate / AI-движок',
    status: 'LIVE',
    stack: ['Groq', 'OpenRouter', 'Claude', 'Gemini', 'Qwen', 'Llama', 'Mixtral', '7 fallback levels', 'auto-blacklist'],
    metric: '7 fallback levels, 0 downtime',
    lightMetric: 'auto model selection, budget control',
    tagline: '7 fallback levels, auto model calibration, 0 downtime',
    lightTagline: 'Smart routing between AI models: auto-selects best by speed and cost',
    title: 'Autonomous LLM Runtime — Multi-Model Cascade',
    description: 'Dynamic model discovery every 12h. Groq→OpenRouter→Bootstrap cascade. 7 fallback levels. Auto-blacklist dead models. Budget gate $5/day.',
    body: 'Autonomous LLM Runtime — система маршрутизации между AI-моделями с 7 уровнями отказоустойчивости.\n\n**Динамическое обнаружение:** каждые 12 часов система опрашивает API Groq и OpenRouter, получает список доступных моделей, фильтрует по критериям (цена, контекст, скорость), ранжирует и кеширует в Redis.\n\n**Каскад:** Groq (бесплатный, 0.5с) → OpenRouter (free-tier модели) → Bootstrap fallback (Llama 3.3 70B). Если модель возвращает 403/404/пустой ответ — автоматический blacklist на 1 час.\n\n**7 моделей в ротации:** Groq, OpenRouter, Claude, Gemini, Qwen, Llama, Mixtral. Система сама выбирает оптимальную по задаче.\n\n**Budget gate:** дневной лимит $5. Алерт при 80%. Premium модели автоматически блокируются при превышении.',
    lightBody: 'Система автоматически выбирает AI-модель для каждого запроса — по скорости, качеству и стоимости. 7 уровней подстраховки: если одна модель упала, подключается следующая.\n\n7 моделей в ротации. Обнаружение новых моделей каждые 12 часов. Контроль бюджета: дневной лимит, алерт при приближении к потолку.',
    howItWorks: 'Request → ModelCascadeRunner selects model (from Redis cache) → attempt → if fail → next fallback (7 levels) → auto-blacklist dead models (1h). ModelDiscoveryJob runs every 12h: Groq API + OpenRouter API → filter by criteria (model_cascade.yml) → rank → cache to Redis.',
    lightHowItWorks: 'Запрос → система выбирает лучшую модель → если не отвечает, переключается на следующую (7 уровней) → контроль бюджета.',
    related: ['dual-brain-chat', 'artifact-pipeline', 'tokenomics-guard'],
  },
  {
    slug: 'dual-brain-chat',
    name: 'Dual-Brain Chat',
    group: 'ai-engine',
    groupLabel: 'Corporate / AI Engine',
    lightGroupLabel: 'Corporate / AI-движок',
    status: 'LIVE',
    stack: ['Groq 0.5s', 'Claude', 'load balancing', 'escalation', 'de-escalation', '-90% tokens'],
    metric: '5 triggers, 0.5s → Claude',
    lightMetric: 'fast + smart, -90% cost',
    tagline: 'Fast brain for simple, smart for complex. Auto-switches',
    lightTagline: 'Fast brain for simple, smart for complex. Auto-switches',
    title: 'Dual-Brain Chat — Intelligent Model Balancing',
    description: 'Two-brain architecture: Groq (0.5s, free) for standard queries, Claude for complex. 5 escalation triggers. Auto de-escalation. 90% token savings.',
    body: 'Dual-Brain — двухмозговая архитектура чата. 80% сообщений обрабатывает быстрый мозг (Groq, бесплатно, 0.5с). 20% — умный мозг (Claude, платно).\n\n**5 триггеров эскалации:**\n1. Негативный тон — слова-маркеры фрустрации\n2. Стагнация — нет новых фактов 4+ сообщений\n3. Повторы — >60% совпадение слов\n4. Явный запрос — пользователь просит\n5. Техническая сложность — intent = artifact или complex analysis\n\n**Деэскалация:** когда разговор нормализуется — автоматический возврат на быстрый мозг. Без уведомления пользователя.\n\n**Экономика:** средняя стоимость сессии $0.12 → $0.01. Экономия 90% токенов без потери качества.',
    lightBody: 'Простые вопросы — мгновенный ответ за 0.5 секунды. Сложная ситуация или фрустрация — автоматическое подключение продвинутой модели.\n\n5 триггеров переключения: негативный тон, стагнация, повторы, явный запрос, сложная задача. Обратное переключение — автоматическое.\n\nЭкономия 90% на AI без потери качества.',
    howItWorks: 'Message → EscalationDetectorService (5 triggers: sentiment, stagnation, repetition, explicit, complexity) → if escalated: Claude via OpenRouter. If normal: Groq (0.5s). De-escalation: LLM sends UI action when conversation normalizes.',
    lightHowItWorks: 'Сообщение → анализ 5 триггеров → простое = быстрая модель (0.5с) / сложное = продвинутая модель → автоматический возврат.',
    related: ['autonomous-llm-runtime', 'semantic-memory', 'tokenomics-guard'],
  },
  {
    slug: 'semantic-memory',
    name: 'Semantic Memory',
    group: 'ai-engine',
    groupLabel: 'Corporate / AI Engine',
    lightGroupLabel: 'Corporate / AI-движок',
    status: 'LIVE',
    stack: ['pg_vector', 'cosine similarity', '19 data points', 'project brief'],
    metric: '19 data points, vector search',
    lightMetric: 'semantic search, data tracking',
    tagline: 'Vector search by meaning + auto-tracking 19 AJTBD data points',
    lightTagline: 'Platform remembers everything: search by meaning, not keywords',
    title: 'Semantic Memory — Vector Search & Data Point Tracking',
    description: 'pg_vector embeddings + cosine similarity for semantic search. Auto-tracking 19 AJTBD data points. Project brief (~300 tokens) instead of full history.',
    body: 'Semantic Memory — система памяти платформы. Два компонента:\n\n**Векторный поиск:** все факты из разговоров сохраняются как pg_vector embeddings. Поиск по смыслу, а не по ключевым словам. "Проблема с зарядкой" найдёт "долго заряжается" и "нет свободных станций".\n\n**Трекинг data points:** 19 AJTBD-полей (ниша, боли, аудитория, экономика, конкуренты...) отслеживаются автоматически. Система знает: какие данные уже есть, каких не хватает, и направляет разговор.\n\n**Project Brief:** сжатое описание проекта (~300 токенов) вместо полной истории (~25K токенов). Генерируется после каждого нового факта. Экономия: запрос 2K токенов вместо 25K.',
    lightBody: 'Все факты из разговоров сохраняются и ищутся по смыслу, а не по ключевым словам. Автоматический трекинг: какие данные о проекте уже есть, каких не хватает.\n\nСжатое описание проекта (~300 токенов) вместо полной истории — экономия 90% на каждый запрос к AI.',
    howItWorks: 'New fact → EmbeddingJob (vector embedding) → pg_vector storage. Search: query → embedding → cosine similarity → top-K results. DpCoverageService maps facts to 19 AJTBD points. BriefUpdaterJob regenerates project brief after each fact.',
    lightHowItWorks: 'Новый факт → сохранение как вектор → поиск по смыслу. Трекинг 19 полей: система знает что собрано, чего не хватает.',
    related: ['vector-intelligence', 'knowledge-graph', 'pain-extractor'],
  },
  {
    slug: 'vector-intelligence',
    name: 'Vector Intelligence Engine',
    group: 'ai-engine',
    groupLabel: 'Corporate / AI Engine',
    lightGroupLabel: 'Corporate / AI-движок',
    status: 'LIVE',
    stack: ['text→facts→vectors→graph', 'pg_vector', '5 dimensions', 'SQLite fallback'],
    metric: '4 levels, pg_vector, 5 dimensions',
    lightMetric: '4 levels of data processing',
    tagline: '4-level data model: text → facts → vectors → graph',
    lightTagline: 'Multi-level analysis: from raw text to knowledge graph automatically',
    title: 'Vector Intelligence Engine — 4-Level Data Pipeline',
    description: 'Raw messages → LLM extraction → structured facts (5 dimensions) → pg_vector embeddings → Knowledge Graph. Each level enriches the previous.',
    body: 'Vector Intelligence — четырёхуровневый pipeline обработки данных:\n\n**Level 1: Raw text** — сообщения пользователя, как есть.\n**Level 2: Structured facts** — LLM извлекает факты по 5 измерениям (niche, pain, audience, economics, competitive). Каждый факт имеет вес 10-100.\n**Level 3: Vector embeddings** — pg_vector для семантического поиска. Cosine similarity.\n**Level 4: Knowledge Graph** — факты становятся узлами, связи между ними — рёбрами.\n\nКаждый уровень обогащает предыдущий. SQLite fallback для dev-среды (без pg_vector).',
    lightBody: 'Четыре уровня обработки: сырой текст → структурированные факты → векторные связи → граф знаний. Каждый уровень обогащает предыдущий.\n\n5 измерений анализа: ниша, боли, аудитория, экономика, конкуренты.',
    howItWorks: 'Message → FactExtractorService (LLM, 5 dimensions) → weight 10-100 → EmbeddingJob (pg_vector) → KgBuilderJob (nodes + edges). SQLite fallback: hash-based embeddings for dev.',
    lightHowItWorks: 'Сообщение → AI извлекает факты → векторизация → граф знаний. Автоматически, для каждого сообщения.',
    related: ['semantic-memory', 'knowledge-graph', 'pain-extractor'],
  },
  {
    slug: 'knowledge-graph',
    name: 'Knowledge Graph',
    group: 'ai-engine',
    groupLabel: 'Corporate / AI Engine',
    lightGroupLabel: 'Corporate / AI-движок',
    status: 'LIVE',
    stack: ['14 node types', '18 edge types', 'confidence scoring', 'evidence trail', 'Rails engine'],
    metric: '14 node types, edges, evidence trail',
    lightMetric: '14 object types, traceability',
    tagline: 'Graph storage: 14 node types, evidence trail to user words',
    lightTagline: 'Knowledge graph: connections between facts, trace to client words',
    title: 'Knowledge Graph — Evidence-Based Intelligence',
    description: 'Rails engine. 14 node types: pain, job, segment, competitor, feature, trend. 18 edge types with confidence. Full traceability: recommendation → fact → user message.',
    body: 'Knowledge Graph — графовое хранилище знаний. Отдельный Rails engine.\n\n**14 типов узлов:** pain, job, segment, competitor, feature, trend, metric, constraint, person, channel, solution, trigger, emotion, criteria.\n\n**18 типов связей:** experiences, causes, addresses, threatens, enables, weakens, competes_with, и другие. Каждая связь имеет weight (0-100) и confidence (0-100).\n\n**Evidence trail:** каждая рекомендация системы прослеживается до конкретных слов пользователя. Не "AI так считает", а "на основании факта X из сообщения #14".\n\n**Автоматическое построение:** KgBuilderJob извлекает сущности из каждого нового факта через Groq. Дедупликация через LLM. Confidence decay: -5 в месяц для старых узлов, удаление ниже 10.\n\n**Query API:** 8 эндпоинтов — graph, nodes, subgraph, evidence, summary, gaps, export, health.',
    lightBody: '14 типов объектов: боли, задачи, сегменты, конкуренты, тренды. Все связи между ними с оценкой уверенности.\n\nПолная трассируемость: любая рекомендация — до конкретных слов пользователя. Не "AI так считает", а "на основании таких-то данных".\n\n8 API-эндпоинтов для запросов к графу.',
    howItWorks: 'New fact → KgBuilderJob (Groq LLM extraction) → nodes + edges with confidence → dedup (LLM fallback) → ActionCable broadcast. Monthly: confidence decay (-5), delete below 10. API: evidence_trail, subgraph, graph_stats, gaps.',
    lightHowItWorks: 'Новый факт → AI извлекает объекты и связи → граф обновляется → трассировка до источника.',
    related: ['vector-intelligence', 'semantic-memory', 'competitive-intelligence'],
  },
  {
    slug: 'ai-discovery-engine',
    name: 'AI Discovery Engine',
    group: 'ai-engine',
    groupLabel: 'Corporate / AI Engine',
    lightGroupLabel: 'Corporate / AI-движок',
    status: 'LIVE',
    stack: ['DuckDuckGo', 'Telegram', 'vc.ru', 'Habr', '3 rounds', 'cache 90d'],
    metric: '3 rounds, cache 90d',
    lightMetric: 'automatic research in minutes',
    tagline: 'Autonomous research: search → TG channels → articles → LLM filtering',
    lightTagline: 'Automatic market research: channels, articles, insights by niche',
    title: 'AI Discovery Engine — Autonomous Market Research',
    description: '3-round research pipeline. DuckDuckGo + Telegram channel validation + article extraction (vc.ru, Habr). LLM filters relevant insights. 90-day cache.',
    body: 'AI Discovery Engine — автономное исследование рынка. Многораундовый pipeline:\n\n**Раунд 1:** LLM генерирует поисковые запросы по нише → DuckDuckGo search → валидация TG-каналов (подписчики ≥50, последний пост <90 дней, фильтр ботов) → fetch постов с пагинацией (~60 постов).\n\n**Раунд 2:** Извлечение полных текстов статей (vc.ru JSON state, Habr, generic readability) → LLM фильтрует только релевантные инсайты.\n\n**Раунд 3:** Если <5 инсайтов — повторный поиск с уточнёнными запросами.\n\n**Кеширование:** посты 24ч, статьи 7д, инсайты 90д, ниши — навсегда. SHA256 дедупликация. Один раз исследовал нишу — все пользователи получают данные.\n\n**NicheMatcher:** двухуровневый матчинг — keyword LIKE → LLM fallback для нечётких совпадений.',
    lightBody: 'AI автоматически исследует рынок: находит релевантные TG-каналы, статьи на vc.ru и Habr, фильтрует только полезные инсайты.\n\nТри раунда углубления. Результаты кешируются 90 дней — повторный запрос по той же нише бесплатен.',
    howItWorks: 'Query → NicheMatcher (keyword + LLM) → cache check → if gaps: DuckDuckGo search → TG channel validation (subscribers ≥50) → fetch posts (pagination) → article extraction → LLM filter → persist to research_* tables. 3 rounds max.',
    lightHowItWorks: 'Запрос → поиск каналов и статей → AI фильтрует релевантное → результат. До 3 раундов углубления.',
    related: ['research-corpus', 'competitive-intelligence', 'trend-monitoring'],
  },

  // ═══════════════════════════════════════
  // CORPORATE / PRODUCT INTELLIGENCE
  // ═══════════════════════════════════════
  {
    slug: 'aicpo-platform',
    name: 'AICPO Platform',
    group: 'product-intel',
    groupLabel: 'Corporate / Product Intelligence',
    lightGroupLabel: 'Corporate / Продуктовая аналитика',
    status: 'LIVE',
    url: 'https://aicpo.ru',
    stack: ['Rails 8', 'PostgreSQL', 'Docker', 'ActionCable', 'SSE', '31 subsystems', '43 artifacts'],
    metric: '43 artifacts, 31 subsystems',
    lightMetric: '43 documents, 31 subsystems',
    tagline: 'AI workspace for product research. 31 subsystems, 43 artifacts',
    lightTagline: 'AI assistant for product research. 31 subsystems, 43 documents',
    title: 'AICPO Platform — AI Product Intelligence',
    description: 'Full-stack SaaS for product teams. Chat with AI → fact extraction → 43 strategic artifacts. Rails 8, multi-model LLM cascade, 3-panel workspace.',
    body: 'AICPO — флагманская платформа. SaaS для продуктовых команд: чат с AI, который помогает исследовать рынок.\n\n**Как работает:** пользователь общается с AI в чате → система автоматически извлекает факты → строит Knowledge Graph → генерирует 43 стратегических артефакта (от JTBD-карт до финансовых моделей).\n\n**31 подсистема:** AI Engine (LLM Runtime, Dual-Brain, Semantic Memory, Vector Intelligence, Knowledge Graph, Discovery), Product Intelligence (Artifact Pipeline, Pain Extractor, Research Corpus, Competitive Intelligence, Trend Monitoring), Self-Evolution, Enterprise, Integrations.\n\n**Стек:** Rails 8, PostgreSQL, Docker, ActionCable (SSE streaming), Propshaft. Kamal deploy. Nginx, SSL. Timeweb VDS.\n\n**Первая отраслевая сборка** на фрейме nevrai. Модули переиспользуемы для других отраслей.',
    lightBody: 'Платформа для продуктовых команд. Чат с AI → автоматическое извлечение фактов → 43 стратегических документа.\n\n31 подсистема: от интеллектуального чата до графа знаний и мониторинга конкурентов. Живой продукт в продакшене.\n\nПервая отраслевая сборка на фрейме nevrai — модули переиспользуемы для других отраслей.',
    howItWorks: 'User message → IntentGateService → ScoreCalculatorJob (fact extraction, DP coverage, brief update, KG build, embedding) → artifact unlock → generation (Structure→Generate→Validate). 3-panel workspace: chat + context + preview.',
    lightHowItWorks: 'Сообщение → AI извлекает факты → обновляет граф знаний → разблокирует документы → генерация по мере накопления данных.',
    related: ['knowledge-graph', 'artifact-pipeline', 'autonomous-llm-runtime'],
  },
  {
    slug: 'artifact-pipeline',
    name: 'Artifact Pipeline',
    group: 'product-intel',
    groupLabel: 'Corporate / Product Intelligence',
    lightGroupLabel: 'Corporate / Продуктовая аналитика',
    status: 'LIVE',
    stack: ['Groq→Gemini→Groq', 'structure', 'generate', 'validate', 'retry', '43 types'],
    metric: '43 types, 3 stages',
    lightMetric: '43 documents with quality check',
    tagline: '3-stage generation: Structure → Generate → Validate → retry',
    lightTagline: '43 strategic documents: from JTBD maps to financial models',
    title: 'Artifact Pipeline — AI Document Generation with Quality Gate',
    description: '43 artifact types. Pipeline: Groq structures → Gemini generates → Groq validates. Auto-retry if score <0.5. A/B model testing via ?model= parameter.',
    body: 'Artifact Pipeline — трёхступенчатая генерация стратегических документов.\n\n**43 типа артефактов:** JTBD-карты, сегментация, unit economics, конкурентный анализ, PRD, landing structure, pitch deck, persona cards, interview scripts, outreach, pricing model, feature priority, value proposition, trend radar, opportunity map, roadmap recommendations и другие.\n\n**Pipeline:**\n1. **Structure** (Groq) — строит outline документа\n2. **Generate** (Gemini) — генерирует полный текст\n3. **Validate** (Groq) — проверяет качество (score 0-1)\n4. **Retry** — если score <0.5, перегенерация\n\n**Staleness detection:** при появлении новых фактов — hash mismatch → артефакт помечается stale → жёлтый баннер "данные обновились".\n\n**A/B testing:** параметр ?model= позволяет сравнить генерацию разными моделями.',
    lightBody: '43 типа стратегических документов. Каждый проходит три этапа: структурирование → генерация → проверка качества.\n\nЕсли качество ниже порога — автоматическая переделка. При появлении новых данных — документы помечаются как устаревшие.',
    howItWorks: 'Request → structure_outline (Groq) → generate (Gemini/OpenRouter) → validate_artifact (Groq, score 0-1) → if <0.5 retry. Staleness: facts_hash + prompt_hash comparison after new facts.',
    lightHowItWorks: 'Запрос → структура → генерация → проверка качества → автоматическая переделка если ниже порога.',
    related: ['aicpo-platform', 'pain-extractor', 'research-corpus'],
  },
  {
    slug: 'pain-extractor',
    name: 'Pain Extractor',
    group: 'product-intel',
    groupLabel: 'Corporate / Product Intelligence',
    lightGroupLabel: 'Corporate / Продуктовая аналитика',
    status: 'LIVE',
    stack: ['Rails engine', 'Groq', 'TG', 'Discord', 'Slack', 'WhatsApp', '19 fields'],
    metric: '4 messengers → 19 fields',
    lightMetric: '4 messengers, auto-analysis',
    tagline: 'Chat export parser → 19 AJTBD data points',
    lightTagline: 'Upload chat export → get structured analysis',
    title: 'Pain Extractor — Chat Export to AJTBD Data Points',
    description: 'Rails engine. Upload TG/Discord/Slack/WhatsApp export → depersonalization → LLM extracts 19 structured fields → JSON.',
    body: 'Pain Extractor — отдельный Rails engine для извлечения инсайтов из переписок.\n\n**Поддерживаемые форматы:** Telegram, Discord, Slack, WhatsApp (JSON/HTML/TXT export).\n\n**Pipeline:** загрузка → деперсонализация (удаление имён, телефонов, email) → LLM извлекает 19 AJTBD data points → структурированный JSON.\n\n**19 полей:** niche, pains (массив), audience, jobs (statement + type + level), triggers, current_solutions, satisfaction, frequency, willingness_to_pay, economics, competitive_landscape, switch_triggers, barriers, desired_outcomes, emotional_jobs, social_jobs, constraints, success_metrics, decision_criteria.',
    lightBody: 'Загрузите экспорт чата из Telegram, Slack, Discord или WhatsApp. AI автоматически извлечёт ключевые данные: боли, задачи, сегменты, триггеры, текущие решения, готовность платить.\n\n19 структурированных полей. Деперсонализация перед анализом.',
    howItWorks: 'File upload → format detection (TG/Discord/Slack/WA) → depersonalization (regex: names, phones, emails) → LLM extraction (Groq, 19 AJTBD fields) → structured JSON.',
    lightHowItWorks: 'Загрузка экспорта → деперсонализация → AI извлекает 19 полей → структурированный результат.',
    related: ['aicpo-platform', 'semantic-memory', 'research-corpus'],
  },
  {
    slug: 'research-corpus',
    name: 'Research Corpus',
    group: 'product-intel',
    groupLabel: 'Corporate / Product Intelligence',
    lightGroupLabel: 'Corporate / Продуктовая аналитика',
    status: 'LIVE',
    stack: ['PostgreSQL', 'SHA256 dedup', 'cross-user', 'TTL 90d'],
    metric: 'cross-user, TTL 90d',
    lightMetric: 'shared base, no repeated searches',
    tagline: 'Shared knowledge base: one research — data for everyone',
    lightTagline: 'Shared research base: research once — data available for all',
    title: 'Research Corpus — Shared Intelligence Cache',
    description: 'Research niches, channels, posts, articles, insights — cached and shared across users. SHA256 dedup. TTL: posts 24h, articles 7d, insights 90d.',
    body: 'Research Corpus — shared база исследований. Результаты рисерча сохраняются и переиспользуются.\n\n**Структура:** research_niches (slug + keywords) → research_channels (TG metadata) → research_posts (SHA256 dedup) → research_articles (url, snippet, full_text) → research_insights (LLM-filtered).\n\n**Cross-user:** если кто-то уже исследовал нишу "EV charging" — данные доступны следующему пользователю без повторного поиска.\n\n**TTL:** посты 24ч (быстро устаревают), статьи 7д, инсайты 90д, ниши — навсегда.\n\n**Приватность:** research_* таблицы shared, workspace_* — приватные per user.',
    lightBody: 'Результаты исследований сохраняются в общую базу. Если кто-то уже изучал похожую нишу — данные доступны сразу, без повторного поиска.\n\nОбновление: посты — каждые 24 часа, статьи — каждую неделю, инсайты — каждые 3 месяца.',
    howItWorks: 'Query → NicheMatcher → cache check (enough fresh insights?) → if gaps: full ResearchService pipeline → persist to research_* tables. SHA256 dedup for posts. Privacy: research_* shared, workspace_* private.',
    lightHowItWorks: 'Запрос → проверка кеша → если данных достаточно, возврат из базы → если нет, запуск нового исследования.',
    related: ['ai-discovery-engine', 'competitive-intelligence', 'trend-monitoring'],
  },
  {
    slug: 'competitive-intelligence',
    name: 'Competitive Intelligence',
    group: 'product-intel',
    groupLabel: 'Corporate / Product Intelligence',
    lightGroupLabel: 'Corporate / Продуктовая аналитика',
    status: 'LIVE',
    stack: ['DuckDuckGo', 'web scrape', 'Groq', 'KG integration', 'cron 6h', 'weekly digest'],
    metric: 'auto-scrape 6h, KG integration',
    lightMetric: 'automatic competitor monitoring',
    tagline: 'Competitor monitoring: auto-scrape, signals, digest',
    lightTagline: 'Competitor monitoring: automatic tracking of changes and threats',
    title: 'Competitive Intelligence — Automated Competitor Monitoring',
    description: 'Auto-detect competitors from chat facts. Web scrape every 6h + DuckDuckGo news. Signal analysis: relevance, threat mapping, KG integration. Weekly digest.',
    body: 'Competitive Intelligence — автоматический мониторинг конкурентов.\n\n**Автодетекция:** CompetitiveAutoDetectService извлекает имена конкурентов из фактов чата. Не нужно вручную добавлять — система сама находит.\n\n**Мониторинг:** SchedulerJob каждые 6 часов → WebScrapeJob (fetch + diff страниц) + NewsSearchJob (DuckDuckGo). Сигналы: relevance scoring (Groq), threat mapping.\n\n**KG-интеграция:** сигналы создают узлы (competitor, feature) и связи (threatens, weakens, enables) в Knowledge Graph.\n\n**Staleness:** critical/act сигналы автоматически помечают competitor_map артефакт как stale.\n\n**Digest:** еженедельный дайджест с приоритизированными сигналами. ActionCable для real-time алертов.',
    lightBody: 'Система автоматически находит конкурентов из данных проекта. Отслеживает их сайты и новости каждые 6 часов. Оценивает угрозы и формирует еженедельный дайджест.\n\nКритические сигналы приходят в реальном времени.',
    howItWorks: 'AutoDetectService (from facts) → Competitor records. SchedulerJob (6h) → WebScrapeJob (fetch+diff) + NewsSearchJob (DDG). AnalyzeNewSignalsJob: Groq relevance + threat → KG nodes/edges. DigestJob (weekly). CompetitiveChannel for real-time alerts.',
    lightHowItWorks: 'Автодетекция конкурентов → мониторинг каждые 6 часов → оценка угроз → еженедельный дайджест.',
    related: ['trend-monitoring', 'ai-discovery-engine', 'knowledge-graph'],
  },
  {
    slug: 'trend-monitoring',
    name: 'Trend Monitoring',
    group: 'product-intel',
    groupLabel: 'Corporate / Product Intelligence',
    lightGroupLabel: 'Corporate / Продуктовая аналитика',
    status: 'LIVE',
    stack: ['DuckDuckGo', 'Jaccard similarity', 'Groq', 'KG', 'weekly', '3 artifacts'],
    metric: 'weekly scan, 3 artifacts',
    lightMetric: 'weekly trend search',
    tagline: 'Trend monitoring: DuckDuckGo → clustering → KG → 3 artifacts',
    lightTagline: 'Trend monitoring in niche: automatic search and impact assessment',
    title: 'Trend Monitoring — Niche Trend Detection & Analysis',
    description: 'Weekly monitoring per niche. Jaccard similarity clustering. LLM niche relevance scoring. KG: trend nodes + pain/job edges. 3 artifacts: trend_radar, opportunity_map, roadmap_recommendations.',
    body: 'Trend Monitoring — еженедельный мониторинг трендов по нишам проектов.\n\n**Pipeline:** MonitorJob (Sunday 6am) → DuckDuckGo search по ключевым словам ниши → для каждого активного проекта.\n\n**Анализ:** AnalyzerService — niche relevance scoring (Groq), кластеризация сигналов (Jaccard similarity), naming трендов (LLM).\n\n**KG-интеграция:** trend nodes + `addresses` edges (trend→pain) + `enables` edges (trend→job).\n\n**3 новых артефакта:**\n1. **Trend Radar** — impact × certainty matrix\n2. **Opportunity Map** — trends × pains matrix\n3. **Roadmap Recommendations** — priority stack из графа\n\n**Unlock:** trend_radar (niche≥15), opportunity_map (+pain≥15), roadmap (+competitive≥10).',
    lightBody: 'Еженедельный поиск трендов в нише проекта. Кластеризация похожих сигналов. Оценка релевантности для бизнеса.\n\nТри аналитических документа: радар трендов (влияние × уверенность), карта возможностей (тренды × боли), рекомендации для roadmap.',
    howItWorks: 'MonitorJob (weekly) → DDG search per niche keyword → AnalyzerService: Groq relevance scoring → Jaccard clustering → LLM trend naming → KG: trend nodes + addresses/enables edges. 3 artifacts: trend_radar, opportunity_map, roadmap_recommendations.',
    lightHowItWorks: 'Еженедельный поиск → оценка релевантности → кластеризация → три аналитических документа.',
    related: ['competitive-intelligence', 'ai-discovery-engine', 'knowledge-graph'],
  },

  // ═══════════════════════════════════════
  // CORPORATE / SELF-EVOLUTION
  // ═══════════════════════════════════════
  {
    slug: 'self-evolving-prompts',
    name: 'Self-Evolving Prompts',
    group: 'self-evolution',
    groupLabel: 'Corporate / Self-Evolution',
    lightGroupLabel: 'Corporate / Самообучение',
    status: 'LIVE',
    stack: ['weekly cron', 'Groq', 'auto-draft', 'versioning', 'rollback', 'A/B prompts'],
    metric: 'auto-draft weekly',
    lightMetric: 'self-learning from reviews',
    tagline: 'Prompts improve themselves from negative feedback',
    lightTagline: 'System learns from mistakes: AI auto-improves answer quality',
    title: 'Self-Evolving Prompts — Automatic Quality Improvement',
    description: 'Weekly auto-draft prompt improvements from negative feedback. Prompt versioning with performance snapshots. Feedback digest every 24h. Rollback if quality drops.',
    body: 'Self-Evolving Prompts — система автоулучшения промптов.\n\n**Feedback loop:**\n1. Пользователь оценивает ответ (thumbs up/down по 3 параметрам: accuracy, completeness, relevance)\n2. FeedbackDigestJob (ежедневно) — агрегирует негативные отзывы\n3. PromptImprovementJob (еженедельно, Monday 5:30am) — AI анализирует паттерны, предлагает конкретные изменения\n4. Версионирование: старая версия сохраняется в workspace_artifact_prompt_versions\n5. Performance snapshot: метрики до и после\n6. Если стало хуже — автооткат\n\n**Chat Audit (параллельный канал):** ChatAuditJob (weekly) — AI читает все диалоги, находит где бот был бесполезен, генерирует задачи в evolution_backlog.',
    lightBody: 'Каждую неделю AI анализирует негативные отзывы и предлагает улучшения. Версионирование: можно откатить если стало хуже. Замер качества до и после.\n\nПараллельно: AI анализирует все диалоги и находит где бот был бесполезен.',
    howItWorks: 'User feedback (3 dimensions) → FeedbackDigestJob (daily) → PromptImprovementJob (weekly, Groq) → auto-draft changes → versioning (prompt_versions table) → performance snapshot → rollback if degraded. ChatAuditJob: weekly session analysis → evolution_backlog.',
    lightHowItWorks: 'Отзывы → ежедневная сводка → еженедельный AI-анализ → предложение улучшений → версионирование с откатом.',
    related: ['evolution-pipeline', 'quality-management', 'incident-to-feature'],
  },
  {
    slug: 'evolution-pipeline',
    name: 'Evolution Pipeline',
    group: 'self-evolution',
    groupLabel: 'Corporate / Self-Evolution',
    lightGroupLabel: 'Corporate / Самообучение',
    status: 'LIVE',
    stack: ['Claude Sonnet', 'Groq', 'daily digest', 'weekly analysis', 'voting', 'prioritization'],
    metric: 'Feedback → AI → Backlog',
    lightMetric: 'AI-prioritized improvements',
    tagline: 'AI generates backlog from feedback and chat audit',
    lightTagline: 'Automatic roadmap: AI analyzes feedback and prioritizes improvements',
    title: 'Evolution Pipeline — AI-Driven Product Backlog',
    description: 'Feedback → Daily digest → Weekly AI analysis (Claude Sonnet) → Prioritized backlog. Chat audit (Groq). Users vote on custom artifacts, vote ≥3 → promotion.',
    body: 'Evolution Pipeline — AI-управляемый бэклог.\n\n**Три источника:**\n1. **Feedback Digest** (daily) — агрегирует отзывы по артефактам за последние 7 дней\n2. **Evolution Analysis** (weekly, Claude Sonnet) — AI анализирует паттерны → генерирует приоритизированные задачи\n3. **Chat Audit** (weekly, Groq) — анализ чат-сессий → паттерны → задачи\n\n**Voting:** пользователи запрашивают custom artifacts → другие голосуют → vote ≥3 → кандидат на промоушен → Ship Pipeline.\n\n**DevBugfixLogger:** баги из разработки автоматически попадают в backlog (8 категорий).\n\n**Результат:** самоуправляемый roadmap. Продукт развивается на основе данных, а не мнений.',
    lightBody: 'Отзывы пользователей → ежедневная сводка → AI-анализ каждую неделю → приоритизированный план улучшений.\n\nПользователи голосуют за нужные фичи. Набравшие 3+ голоса — в работу автоматически.',
    howItWorks: 'FeedbackDigestJob (daily 3am) → EvolutionAnalysisJob (weekly Monday 4am, Claude Sonnet) → evolution_backlog (priority scored). ChatAuditJob (weekly 5am, Groq) → evolution_backlog. Custom artifacts: POST → vote → ≥3 → Ship Pipeline.',
    lightHowItWorks: 'Ежедневная сводка отзывов → еженедельный AI-анализ → приоритизированный план → голосование пользователей.',
    related: ['self-evolving-prompts', 'ship-pipeline', 'quality-management'],
  },
  {
    slug: 'ship-pipeline',
    name: 'Ship Pipeline',
    group: 'self-evolution',
    groupLabel: 'Corporate / Self-Evolution',
    lightGroupLabel: 'Corporate / Самообучение',
    status: 'LIVE',
    stack: ['ActionCable', 'Groq', 'vote ≥3', 'auto-generate', 'notify'],
    metric: 'vote → promote → auto-generate',
    lightMetric: 'voting → auto-generation',
    tagline: 'Vote → promote → auto-generate → notify. Product evolves itself',
    lightTagline: 'Users vote for features → AI generates → product evolves itself',
    title: 'Ship Pipeline — User-Driven Feature Delivery',
    description: 'Users request custom artifacts → others vote → vote ≥3 → admin promotes → LLM auto-generates → ActionCable notification. Self-managing backlog.',
    body: 'Ship Pipeline — самоуправляемая система доставки фич.\n\n**Flow:**\n1. Пользователь запрашивает custom artifact (POST /api/custom_artifacts)\n2. Другие пользователи голосуют (POST /api/custom_artifacts/:id/vote)\n3. vote ≥3 → кандидат на промоушен\n4. Admin нажимает Ship (PATCH /api/backlog/:id {status: "promoted"})\n5. CustomArtifactGeneratorJob автоматически генерирует через LLM\n6. ActionCable уведомляет заинтересованных пользователей\n\n**Результат:** продукт развивается на основе реального спроса, а не product roadmap.',
    lightBody: 'Пользователи запрашивают документы → другие голосуют → набравшие 3+ голоса → AI генерирует автоматически → уведомление всем заинтересованным.\n\nПродукт развивается на основе реального спроса.',
    howItWorks: 'POST /api/custom_artifacts → vote → ≥3 → PATCH /api/backlog/:id (promoted) → CustomArtifactGeneratorJob (Gemini Flash) → ActionCable broadcast.',
    lightHowItWorks: 'Запрос → голосование → 3+ голоса → автогенерация → уведомление.',
    related: ['evolution-pipeline', 'self-evolving-prompts', 'quality-management'],
  },
  {
    slug: 'quality-management',
    name: 'Quality Management',
    group: 'self-evolution',
    groupLabel: 'Corporate / Self-Evolution',
    lightGroupLabel: 'Corporate / Самообучение',
    status: 'LIVE',
    stack: ['accuracy', 'completeness', 'relevance', 'staleness detection', 'prompt versioning'],
    metric: '3 dimension feedback, auto-draft',
    lightMetric: '3 parameters, auto-improvement',
    tagline: 'Quality management: feedback → improvement → versioning',
    lightTagline: 'Quality management: reviews → improvement → versioning',
    title: 'Quality Management — Feedback-Driven Improvement Cycle',
    description: 'Thumbs per dimension (Accuracy/Completeness/Relevance). Daily feedback digest. Weekly prompt auto-improvement. Staleness detection (facts_hash + prompt_hash).',
    body: 'Quality Management — управление качеством AI-генерируемого контента.\n\n**3-dimensional feedback:** каждый артефакт оценивается по трём параметрам:\n- Accuracy — насколько точно\n- Completeness — насколько полно\n- Relevance — насколько по делу\n\n**Staleness detection:** при появлении новых фактов — facts_hash mismatch → артефакт stale. При обновлении промпта — prompt_hash mismatch → stale. UI: жёлтый баннер.\n\n**Prompt versioning:** каждая версия промпта сохраняется с performance snapshot (средние оценки за период). Можно сравнить и откатить.',
    lightBody: 'Оценка по трём параметрам: точность, полнота, релевантность. Ежедневная сводка отзывов. Автоматическое определение устаревших документов. Версионирование промптов.',
    howItWorks: 'Reaction bar (3 thumbs) → workspace_artifact_feedbacks (debounced 1.2s). Staleness: facts_hash + prompt_hash comparison. Prompt versioning: workspace_artifact_prompt_versions with performance snapshots.',
    lightHowItWorks: 'Оценка → сводка → определение устаревших → автоулучшение → версионирование.',
    related: ['self-evolving-prompts', 'evolution-pipeline', 'artifact-pipeline'],
  },
  {
    slug: 'incident-to-feature',
    name: 'Incident → Feature',
    group: 'self-evolution',
    groupLabel: 'Corporate / Self-Evolution',
    lightGroupLabel: 'Corporate / Самообучение',
    status: 'LIVE',
    stack: ['Claude Sonnet', 'Groq', '8 categories', 'chat audit', 'auto-backlog'],
    metric: 'incident → AI analysis → feature',
    lightMetric: 'bug → AI analysis → improvement',
    tagline: 'Incident escalation → features. AI-managed backlog',
    lightTagline: 'Bug → analysis → feature: AI turns incidents into improvements',
    title: 'Incident → Feature Pipeline — AI-Driven Improvement',
    description: 'DevBugfixLogger (8 categories) → evolution_backlog. Negative feedback → Claude Sonnet weekly analysis → prioritized backlog. Chat audit → patterns → backlog.',
    body: 'Incident → Feature — система превращения инцидентов в улучшения.\n\n**DevBugfixLogger:** каждый баг из разработки автоматически попадает в evolution_backlog. 8 категорий: UI, backend, performance, security, data, integration, UX, infrastructure.\n\n**AI Analysis (weekly):** Claude Sonnet анализирует все инциденты за неделю → находит паттерны → генерирует приоритизированные задачи.\n\n**Chat Audit (weekly):** Groq анализирует чат-сессии → находит паттерны стагнации, фрустрации, повторов → задачи в backlog.\n\n**Результат:** каждый баг автоматически становится кандидатом на фичу. Система улучшается из своих ошибок.',
    lightBody: 'Каждый баг и негативный отзыв автоматически анализируется AI. Результат — приоритизированный план улучшений. Инциденты превращаются в фичи.',
    howItWorks: 'DevBugfixLogger (8 categories) → evolution_backlog (source: dev_bugfix). EvolutionAnalysisJob (weekly, Claude Sonnet) → pattern analysis → prioritized tasks. ChatAuditJob (weekly, Groq) → session patterns → backlog.',
    lightHowItWorks: 'Баг → логирование → еженедельный AI-анализ → приоритизированная задача.',
    related: ['evolution-pipeline', 'self-evolving-prompts', 'quality-management'],
  },

  // ═══════════════════════════════════════
  // CORPORATE / ENTERPRISE
  // ═══════════════════════════════════════
  {
    slug: 'team-os',
    name: 'Team OS',
    group: 'enterprise',
    groupLabel: 'Corporate / Enterprise',
    lightGroupLabel: 'Corporate / Корпоративные функции',
    status: 'LIVE',
    stack: ['SAML 2.0', 'OIDC', 'RBAC', '4 roles', 'auto-provisioning', 'audit log', '@AI comments'],
    metric: 'SAML + OIDC, 4 roles',
    lightMetric: 'roles, SSO, audit',
    tagline: 'Organizations, RBAC, SSO (SAML + OIDC), audit log',
    lightTagline: 'Teamwork: roles, SSO authentication, action audit',
    title: 'Team OS — Enterprise Identity & Collaboration',
    description: '4 roles (owner/admin/editor/viewer). SAML 2.0 + OIDC with auto-provisioning. Immutable audit log. Threaded comments with @AI. Artifact tasks.',
    body: 'Team OS — корпоративные функции для командной работы.\n\n**RBAC:** 4 роли — owner, admin, editor, viewer. PermissionService проверяет каждое действие.\n\n**SSO:** SAML 2.0 + OIDC. Конфигурация через API (metadata_url auto-parse или ручная). Auto-provisioning: новый SSO-пользователь получает random password + viewer role. sso_enforced: отключает password login для членов организации.\n\n**Audit log:** immutable записи — organization_id, user_id, action, resource_type, resource_id, metadata, ip_address. Нет updated_at — записи нельзя менять.\n\n**Комментарии:** threaded comments к артефактам. @AI — бот отвечает в треде (AiCommentJob).\n\n**Artifact tasks:** collect/analyze/review задачи per artifact с assignee и reviewer.',
    lightBody: 'Организации с ролями: владелец, администратор, редактор, зритель. Корпоративная авторизация через SAML/OIDC. Аудит-лог всех действий.\n\nКомментарии к документам — @AI бот отвечает в треде. Задачи по артефактам с назначением ответственных.',
    howItWorks: 'OrgMembership (4 roles) → PermissionService.can?(user, action, org). SAML: metadata_url → parse → IdP redirect → callback → provision. OIDC: issuer auto-discovery → redirect → code exchange → JWT/JWKS validation. AuditLog: after_action concern, immutable.',
    lightHowItWorks: 'Роли → проверка прав → SSO авторизация → аудит-лог → комментарии с @AI.',
    related: ['admin-command-center', 'user-management', 'credit-engine'],
  },
  {
    slug: 'crm-engine',
    name: 'CRM Engine',
    group: 'enterprise',
    groupLabel: 'Corporate / Enterprise',
    lightGroupLabel: 'Corporate / Корпоративные функции',
    status: 'LIVE',
    stack: ['AI lead scoring', 'churn detector', 'reactivation', 'referral', '28 campaigns'],
    metric: 'lead scoring, churn, referral',
    lightMetric: 'scoring, churn, referral program',
    tagline: 'CRM: lead scoring, churn detector, reactivation, referral',
    lightTagline: 'CRM: lead scoring, churn detection, reactivation, referral program',
    title: 'CRM Engine — AI-Powered Customer Intelligence',
    description: 'AI lead scoring (daily cron). Churn detector with auto reactivation emails. Referral system (5000 credits per activation). 28 seeded campaigns.',
    body: 'CRM Engine — AI-управляемая CRM.\n\n**Lead Scoring:** LeadScoringJob (daily 3:30am) — AI оценивает каждый лид по активности, глубине использования, паттернам.\n\n**Churn Detector:** ChurnDetectorService определяет пользователей в зоне риска. ReactivationEmailJob (Wednesday 10am) — автоматические email.\n\n**Referral:** User.referral_code, URL param ?ref=CODE. 5000 credits при активации. ActivationTrackerService отслеживает конверсию.\n\n**Campaigns:** 28 засеянных кампаний с UTM-трекингом. CampaignTrackerService привязывает источник к каждому лиду.\n\n**Session Briefing:** SessionBriefingService генерирует контекст для персонализации каждого визита.',
    lightBody: 'AI оценивает лидов ежедневно. Автоматическое определение оттока — реактивационные email. Реферальная программа: бонус за каждого приведённого пользователя.\n\n28 кампаний с UTM-трекингом. Персонализация каждого визита.',
    howItWorks: 'LeadScoringJob (daily) → crm_leads score. ChurnDetectorService → risk flags. ReactivationEmailJob (weekly). Referral: ?ref=CODE → claim → 5000 credits. 28 campaigns seeded. SessionBriefingService for personalization.',
    lightHowItWorks: 'Ежедневный AI-скоринг → определение оттока → автоматическая реактивация → реферальная программа.',
    related: ['marketing-analytics', 'user-management', 'admin-command-center'],
  },
  {
    slug: 'credit-engine',
    name: 'Credit Engine',
    group: 'enterprise',
    groupLabel: 'Corporate / Enterprise',
    lightGroupLabel: 'Corporate / Корпоративные функции',
    status: 'LIVE',
    stack: ['6 tiers', 'atomic deductions', 'row locks', 'BYOK', 'soft limits', 'overdraft'],
    metric: '6 tiers, row locks',
    lightMetric: '6 tiers, transparent spending',
    tagline: 'Atomic transactions with row lock — race condition impossible',
    lightTagline: 'Billing: 6 tiers, transparent spending, overdraft protection',
    title: 'Credit Engine — Enterprise Billing & Metering',
    description: '6 tiers (free → enterprise). Atomic deductions with row locks. Soft limits with overdraft for business. BYOK (Bring Your Own Key) for OpenRouter.',
    body: 'Credit Engine — биллинг и тарификация.\n\n**6 тиеров:** free (100/мес), team (50K), business (100K), enterprise (300K). Soft limit: business/enterprise — овердрафт (счёт потом). Free/team — hard block.\n\n**Atomic deductions:** row lock на PostgreSQL предотвращает race conditions. Idempotency keys.\n\n**BYOK:** организации подключают свой OpenRouter API key (PATCH /api/org/settings). LlmKeyResolver: org key → system ENV fallback.\n\n**Стоимости:** chat_message=1, artifact_generation=5, artifact_regen=3, artifact_premium=10, research=15, custom_artifact=8, connector_import=10.\n\n**UI:** usage % в statusbar (green <80%, yellow 80-100%, red >100%). Transaction history через API.',
    lightBody: '6 тарифных планов: от бесплатного до enterprise. Прозрачный расход: каждое действие имеет стоимость в кредитах. Бизнес-планы допускают перерасход с последующим счётом.\n\nОрганизации могут подключить свой API-ключ OpenRouter.',
    howItWorks: 'CreditService.deduct!(account, amount, action_type, idempotency_key) → row lock → balance check → atomic deduction → transaction log. BYOK: org.settings.openrouter_api_key → LlmKeyResolver.',
    lightHowItWorks: 'Действие → проверка баланса → атомарное списание → лог транзакции.',
    related: ['tokenomics-guard', 'p-l-economics', 'user-management'],
  },
  {
    slug: 'tokenomics-guard',
    name: 'Tokenomics Guard',
    group: 'enterprise',
    groupLabel: 'Corporate / Enterprise',
    lightGroupLabel: 'Corporate / Корпоративные функции',
    status: 'LIVE',
    stack: ['per-request tracking', '$5/day limit', 'alert 80%', 'auto-block premium'],
    metric: '$5/day, alert 80%',
    lightMetric: 'AI budget control',
    tagline: 'Per-request LLM cost tracking, budget gate',
    lightTagline: 'AI spending control: daily limit, alert when approaching ceiling',
    title: 'Tokenomics Guard — LLM Budget Control',
    description: 'Per-request token usage and cost tracking. Model pricing table. Daily budget $5 (LLM_DAILY_BUDGET_USD). Alert at 80%. Auto-block premium models on exceed.',
    body: 'Tokenomics Guard — контроль расходов на AI.\n\n**Per-request tracking:** каждый LLM-запрос записывается в workspace_llm_usages: model_id, action, input_tokens, output_tokens, estimated_cost_usd.\n\n**Model pricing:** free models = $0, Claude Sonnet = $3/$15 per million, Haiku = $0.8/$4.\n\n**Budget gate:** LLM_DAILY_BUDGET_USD (default $5). Алерт TG при 80%. budget_exceeded? блокирует premium модели.\n\n**Fallback:** при превышении бюджета — escalated sessions падают на free models (Groq).',
    lightBody: 'Каждый AI-запрос учитывается: модель, объём, стоимость. Дневной лимит бюджета. Алерт при 80% расхода. Дорогие модели автоматически блокируются при превышении.',
    howItWorks: 'TokenomicsService.record!(model, action, input_tokens, output_tokens) → estimated_cost → workspace_llm_usages. budget_exceeded? → daily sum vs LLM_DAILY_BUDGET_USD. Alert at 80% via TG bot.',
    lightHowItWorks: 'Запрос → учёт стоимости → проверка бюджета → алерт при 80% → блокировка при превышении.',
    related: ['autonomous-llm-runtime', 'credit-engine', 'dual-brain-chat'],
  },
  {
    slug: 'p-l-economics',
    name: 'P&L Economics',
    group: 'enterprise',
    groupLabel: 'Corporate / Enterprise',
    lightGroupLabel: 'Corporate / Корпоративные функции',
    status: 'LIVE',
    stack: ['6 tiers', 'per-member analytics', 'transaction history', 'usage %'],
    metric: '6 tiers, soft limits, P&L',
    lightMetric: '6 tiers, spending analytics',
    tagline: 'P&L and unit economics of the platform',
    lightTagline: 'P&L and unit economics of the platform',
    title: 'P&L Economics — Platform Unit Economics',
    description: 'Credit system: 6 tiers, welcome bonus, atomic deductions. Monthly limits. Soft limits with overdraft. Per-member usage analytics. Transaction history.',
    body: 'P&L Economics — юнит-экономика платформы.\n\n**Тарифы:** free (1K credits), beta (15K), team (50K/мес), business (100K/мес), enterprise (300K/мес).\n\n**Per-member analytics:** GET /api/org/usage — расход по каждому члену организации.\n\n**Transaction history:** GET /api/credits/history — полная история с totals.\n\n**Usage %:** отображается в statusbar: green <80%, yellow 80-100%, red >100%.\n\n**Welcome bonus:** 1K для free, 15K для beta (через invite code).',
    lightBody: 'Кредитная система: 6 тарифов, прозрачная экономика. Лимиты по тарифам, аналитика расхода по пользователям, история транзакций.',
    howItWorks: 'CreditAccount (per user/session) → CreditTransaction log → balance tracking. Tiers: free/beta/team/business/enterprise. GET /api/org/usage → per-member breakdown.',
    lightHowItWorks: 'Кредитный аккаунт → лог транзакций → аналитика по пользователям.',
    related: ['credit-engine', 'tokenomics-guard', 'marketing-analytics'],
  },
  {
    slug: 'user-management',
    name: 'User Management',
    group: 'enterprise',
    groupLabel: 'Corporate / Enterprise',
    lightGroupLabel: 'Corporate / Корпоративные функции',
    status: 'LIVE',
    stack: ['invites', '3 tiers', 'shadow projects', 'claim', 'IP rate limit', 'welcome bonus'],
    metric: 'invites, 3 tiers, shadow projects',
    lightMetric: 'invites, tiers, registration',
    tagline: 'User management: invites, tiers, anonymous funnel',
    lightTagline: 'User management: invites, tiers, registration',
    title: 'User Management — Registration & Tier System',
    description: 'Beta invites (8-char codes). 3 tiers (free/beta/admin). Anonymous lockdown: 3 free messages → registration. Shadow projects with claim. IP rate limit.',
    body: 'User Management — управление пользователями и воронкой.\n\n**Shadow Projects:** анонимный пользователь получает реальный DB-проект с session_id. Факты, сообщения, артефакты накапливаются. На регистрации → project.claim!(user) — передача владения.\n\n**Anonymous lockdown:** 3 бесплатных сообщения → gate регистрации (Google OAuth + TG login). IP rate limit: max 10 shadow projects per IP per day.\n\n**Invites:** beta_invites table, 8-char codes. Claim через API или URL param ?invite=CODE. Chat command: "у меня инвайт XXXXXXXX".\n\n**Tiers:** free (1K credits, 2 artifact gens), beta (15K, full access), admin (unlimited).',
    lightBody: 'Инвайт-коды, три тарифа. Анонимные пользователи получают 3 бесплатных сообщения — затем регистрация. Данные сохраняются и привязываются к аккаунту.\n\nБонус кредитов при регистрации.',
    howItWorks: 'Anonymous: session_id → shadow project → 3 free messages → registration gate. Claim: project.claim!(user). Invites: 8-char code → /api/invites/claim → upgrade to beta. Tiers: free/beta/admin with different credit limits.',
    lightHowItWorks: 'Анонимный вход → 3 сообщения → регистрация → данные привязываются → бонус кредитов.',
    related: ['credit-engine', 'team-os', 'admin-command-center'],
  },
  {
    slug: 'admin-command-center',
    name: 'Admin Command Center',
    group: 'enterprise',
    groupLabel: 'Corporate / Enterprise',
    lightGroupLabel: 'Corporate / Корпоративные функции',
    status: 'LIVE',
    stack: ['KPI', 'bulk actions', 'hotkeys', 'CRM', 'backlog', 'TG publish'],
    metric: 'KPI, bulk actions, hotkeys',
    lightMetric: 'unified management dashboard',
    tagline: 'Command center: KPI, CRM, analytics, Ship pipeline, TG channel, invites',
    lightTagline: 'Command center: KPI, CRM, analytics — all in one',
    title: 'Admin Command Center — Unified Operations Dashboard',
    description: 'Full-page KPI dashboard: filterable table, detail panel, bulk actions, keyboard shortcuts. Single command center for all platform operations.',
    body: 'Admin Command Center — единый дашборд управления платформой.\n\n**KPI:** полноэкранная таблица с фильтрами, detail panel при клике, bulk actions.\n\n**Keyboard shortcuts:** навигация по таблице, быстрые действия без мыши.\n\n**Интеграции:** CRM (leads, campaigns), backlog (evolution + custom requests), invites (generation, management), TG channel (publish from admin), health (system status).\n\n**Owner only:** доступ только для owner-аккаунта.',
    lightBody: 'Единый дашборд для управления платформой: метрики, пользователи, контент, инвайты, публикации. Клавиатурные сокращения для быстрой работы.',
    howItWorks: '/admin/* routes → owner-only access. Backlog: KPI, filterable table, detail panel, bulk status updates. Keyboard shortcuts for navigation. CRM, invites, TG publish integrated.',
    lightHowItWorks: 'Одна страница → все операции: метрики, пользователи, контент, публикации.',
    related: ['crm-engine', 'marketing-analytics', 'team-os'],
  },
  {
    slug: 'marketing-analytics',
    name: 'Marketing Analytics',
    group: 'enterprise',
    groupLabel: 'Corporate / Enterprise',
    lightGroupLabel: 'Corporate / Корпоративные функции',
    status: 'LIVE',
    stack: ['PostHog', 'GA4', 'UTM', 'funnel', 'cohorts', '28 campaigns', 'weekly reports'],
    metric: 'funnel, cohorts, 28 campaigns',
    lightMetric: 'funnel, cohorts, campaigns',
    tagline: 'Funnel, cohorts, campaigns, UTM tracking',
    lightTagline: 'Funnel, cohorts, campaigns, UTM tracking',
    title: 'Marketing Analytics — Full Funnel Intelligence',
    description: 'Conversion funnel, cohort analysis, 28 campaigns with UTM tracking. PostHog + GA4 integration. Weekly reports (cron).',
    body: 'Marketing Analytics — полная маркетинговая аналитика.\n\n**Воронка:** awareness → signup → activation → retention → revenue. Каждый этап отслеживается.\n\n**Когорты:** группировка пользователей по дате регистрации, источнику, тарифу. Retention curves.\n\n**28 кампаний:** засеянные при старте с UTM-параметрами. CampaignTrackerService привязывает каждый лид к источнику.\n\n**Интеграции:** PostHog (events, funnels), GA4 (traffic sources), Yandex Metrika (goals).\n\n**Referral tracking:** User.referral_code, ?ref=CODE, 5000 credits on activation.\n\n**Weekly reports:** WeeklyReportJob (Monday 4am) → crm_weekly_reports.',
    lightBody: 'Полная маркетинговая аналитика: воронка конверсии, когортный анализ, 28 кампаний с UTM-трекингом. Интеграция с PostHog и GA4. Еженедельные отчёты.',
    howItWorks: 'crm_page_events → funnel stages. crm_campaigns (28 seeded) → UTM tracking. PostHog + GA4 integration. WeeklyReportJob (Monday 4am) → crm_weekly_reports. Referral: ?ref=CODE → 5000 credits.',
    lightHowItWorks: 'Отслеживание воронки → когорты → UTM-кампании → еженедельные отчёты.',
    related: ['crm-engine', 'admin-command-center', 'user-management'],
  },

  // ═══════════════════════════════════════
  // CORPORATE / INTEGRATIONS
  // ═══════════════════════════════════════
  {
    slug: 'product-health-monitor',
    name: 'Product Health Monitor',
    group: 'integrations',
    groupLabel: 'Corporate / Integrations',
    lightGroupLabel: 'Corporate / Интеграции',
    status: 'LIVE',
    stack: ['PostHog', 'Stripe', 'GA4', 'Metrika', 'YooKassa', 'CloudPayments', '46 integrations'],
    metric: '46 integrations, 28 connectors',
    lightMetric: '46 integrations, live dashboard',
    tagline: 'Live product pulse: 46 integrations, 6 live connectors, 28 in roadmap',
    lightTagline: 'Business metrics monitoring: PostHog, Stripe, GA4, Metrika — in one dashboard',
    title: 'Product Health Monitor — Real-Time Business Metrics',
    description: '46 integrations (12 ready, 8 adapters, 26 planned). 28 monitoring connectors. Real-time pulse, alert rules, ActionCable push. AI diagnosis weekly.',
    body: 'Product Health Monitor — мониторинг бизнес-метрик в реальном времени.\n\n**46 интеграций:** 12 готовых, 8 адаптеров, 26 запланированных. P0 коннекторы: PostHog, Stripe, GA4, Yandex Metrika, YooKassa, CloudPayments.\n\n**Architecture:** Monitoring::Scheduler (каждые 6ч) → Monitoring::SyncJob (per connection) → Monitoring::PulseBuilder → ActionCable push.\n\n**Alert rules:** настраиваемые правила с acknowledgement. GET/POST/PATCH/DELETE /api/monitoring/alert_rules.\n\n**AI diagnosis:** Monitoring::DiagnosisJob (weekly Sunday) — AI анализирует метрики, выявляет аномалии.\n\n**Chat integration:** живые метрики inject в system prompt когда мониторинг активен.',
    lightBody: '46 интеграций с аналитическими сервисами. Живой пульс продукта: выручка, трафик, конверсии — всё в одном месте. Настраиваемые алерты. AI-диагностика каждую неделю.',
    howItWorks: 'MonitoringConnection → SchedulerJob (6h) → SyncJob → PulseBuilder → ActionCable. AlertEngine evaluates rules → MonitoringAlert (with acknowledgement). DiagnosisJob (weekly) → AI analysis. Chat: metrics injected into system prompt.',
    lightHowItWorks: 'Подключение источников → синхронизация каждые 6 часов → пульс → алерты → AI-диагностика.',
    related: ['system-health', 'marketing-analytics', 'admin-command-center'],
  },
  {
    slug: 'email-bridge',
    name: 'Email Bridge',
    group: 'integrations',
    groupLabel: 'Corporate / Integrations',
    lightGroupLabel: 'Corporate / Интеграции',
    status: 'LIVE',
    stack: ['IMAP poll 2min', 'SMTP', 'ActionCable', 'auto-routing', 'bounce protection'],
    metric: 'poll 2min, auto-routing',
    lightMetric: 'incoming + outgoing, auto-routing',
    tagline: 'Bidirectional email channel: IMAP poll → project routing',
    lightTagline: 'Email integration: send and receive emails from the platform',
    title: 'Email Bridge — Bidirectional Email Channel',
    description: 'IMAP poll every 2min. SMTP for invites and artifacts. Routing: In-Reply-To → subject tag → EmailChannel → User. Auto-reply/bounce detection.',
    body: 'Email Bridge — двусторонний email-канал.\n\n**Outbound:** EmailOutboundService отправляет приглашения и артефакты через SMTP (Timeweb).\n\n**Inbound:** EmailInboundJob — IMAP poll каждые 2 минуты. Маршрутизация: In-Reply-To → subject tag [AICPO-XX] → EmailChannel → User email → reject.\n\n**Security:** auto-reply/bounce detection, attachment validation (тот же whitelist что FileUploadValidator), ephemeral body.\n\n**Data:** email_channels (project↔email link), email_messages (ephemeral in/out records).',
    lightBody: 'Двусторонний email-канал. Отправка приглашений и документов. Входящие письма автоматически попадают в нужный проект. Защита от авто-ответов и bounce.',
    howItWorks: 'EmailOutboundService → SMTP. EmailInboundJob (2min IMAP poll) → routing: In-Reply-To → subject tag [AICPO-XX] → EmailChannel → project. Bounce/auto-reply detection. Attachment validation.',
    lightHowItWorks: 'Отправка через SMTP → входящие через IMAP каждые 2 минуты → автоматическая маршрутизация.',
    related: ['pdf-publisher', 'tg-channel-publisher', 'aicpo-platform'],
  },
  {
    slug: 'pdf-publisher',
    name: 'PDF Publisher',
    group: 'integrations',
    groupLabel: 'Corporate / Integrations',
    lightGroupLabel: 'Corporate / Интеграции',
    status: 'LIVE',
    stack: ['document ID', 'content freeze', 'verification', 'B4 print-ready', 'watermark'],
    metric: 'B4, watermark, public links',
    lightMetric: 'PDF with signature, verification',
    tagline: 'Public PDFs with digital signature: document ID + frozen content + verification',
    lightTagline: 'Document publishing: PDF with signature, authenticity verification, public links',
    title: 'PDF Publisher — Verified Document Publishing',
    description: 'Each document gets unique ID (AICPO-YYYYMM-HEXHEX). Content frozen at creation. Verification by ID. Print-ready B4, watermark, view counter, public access.',
    body: 'PDF Publisher — публикация документов с цифровой подписью.\n\n**Document ID:** каждый документ получает уникальный ID формата AICPO-YYYYMM-HEXHEX.\n\n**Content freeze:** контент замораживается на момент создания — изменить невозможно. Это гарантирует, что полученный документ = тот, который был создан.\n\n**Verification:** GET /pdf/:token — публичный доступ без логина. По ID можно верифицировать подлинность.\n\n**Print-ready:** B4 формат, watermark, clean B&W print. View counter (access_count).\n\n**API:** POST /api/org/pdf_links (создать), GET /api/org/pdf_links (список), DELETE /api/org/pdf_links/:id (отозвать).',
    lightBody: 'Каждый документ получает уникальный ID. Контент замораживается — изменить невозможно. Можно верифицировать подлинность по ID. Публичный доступ без логина, готовность к печати.',
    howItWorks: 'POST /api/org/pdf_links → ArtifactPdfLink (token, document_id, content_snapshot). GET /pdf/:token → public view (pdf layout, print-ready B4). Verification by document_id. Access counter.',
    lightHowItWorks: 'Создание ссылки → заморозка контента → публичный доступ → верификация по ID.',
    related: ['email-bridge', 'artifact-pipeline', 'aicpo-platform'],
  },
  {
    slug: 'tg-channel-publisher',
    name: 'TG Channel Publisher',
    group: 'integrations',
    groupLabel: 'Corporate / Integrations',
    lightGroupLabel: 'Corporate / Интеграции',
    status: 'LIVE',
    stack: ['CF Worker relay', 'Telegram API', 'preview', 'scheduled posts'],
    metric: 'CF Worker relay, TG channel',
    lightMetric: 'publishing from admin',
    tagline: 'Content publishing to TG channel from platform',
    lightTagline: 'Telegram channel publishing from platform',
    title: 'TG Channel Publisher — Telegram Content Management',
    description: 'TG channel management from admin. Cloudflare Worker relay for delivery. Formatting, preview, scheduled publishing.',
    body: 'TG Channel Publisher — управление Telegram-каналом из платформы.\n\n**Cloudflare Worker relay:** CF Worker принимает запрос из админки → пересылает в Telegram API. Это решает проблему блокировки Telegram API из некоторых сетей.\n\n**Функции:** создание постов с форматированием (Markdown), предпросмотр перед отправкой, отложенная публикация.\n\n**Admin UI:** /admin/tg_channel — создание, редактирование, публикация постов.',
    lightBody: 'Управление Telegram-каналом из админки: создание постов, предпросмотр, публикация. Cloudflare Worker relay для надёжной доставки.',
    howItWorks: 'Admin UI → POST to CF Worker (tg-webhook-relay) → Telegram Bot API → channel post. Markdown formatting, preview before send.',
    lightHowItWorks: 'Создание поста в админке → предпросмотр → публикация через CF Worker → Telegram канал.',
    related: ['blog-publisher', 'email-bridge', 'admin-command-center'],
  },
  {
    slug: 'blog-publisher',
    name: 'Blog Publisher',
    group: 'integrations',
    groupLabel: 'Corporate / Integrations',
    lightGroupLabel: 'Corporate / Интеграции',
    status: 'LIVE',
    stack: ['Markdown', 'SEO', 'preview', 'admin panel'],
    metric: 'markdown, SEO, preview',
    lightMetric: 'articles, SEO, preview',
    tagline: 'Blog system with publishing from platform',
    lightTagline: 'Blog system with publishing from platform',
    title: 'Blog Publisher — Content Management & SEO',
    description: 'Blog post creation and management. Markdown + preview. SEO optimization. Publishing from admin panel.',
    body: 'Blog Publisher — блог-система, интегрированная в платформу.\n\n**Создание:** Markdown-редактор с превью. SEO-оптимизация: title, description, OG tags.\n\n**Публикация:** из админ-панели, без деплоя. Мгновенная публикация.\n\n**SEO:** sitemap.xml автогенерация, canonical URLs, структурированные данные.',
    lightBody: 'Создание и публикация статей из админ-панели. Markdown-редактор, SEO-оптимизация, предпросмотр перед публикацией.',
    howItWorks: 'Admin panel → Markdown editor → preview → publish. Auto-generated sitemap.xml, canonical URLs, OG tags.',
    lightHowItWorks: 'Редактор → предпросмотр → публикация → SEO автоматически.',
    related: ['tg-channel-publisher', 'admin-command-center', 'email-bridge'],
  },
  {
    slug: 'system-health',
    name: 'System Health',
    group: 'integrations',
    groupLabel: 'Corporate / Integrations',
    lightGroupLabel: 'Corporate / Интеграции',
    status: 'LIVE',
    stack: ['health check', 'deploy status', 'alerts', 'diagnostics', 'weekly cron'],
    metric: 'health check, deploy status',
    lightMetric: 'monitoring, alerts, diagnostics',
    tagline: 'System health: health check, deploy status, monitoring',
    lightTagline: 'System health monitoring: checks, status, alerts',
    title: 'System Health — Infrastructure Monitoring',
    description: '/admin/health endpoint with deploy_status. Monitoring connections + pulse builder. Scheduled sync jobs. Alert engine with acknowledgement. Weekly diagnostics.',
    body: 'System Health — мониторинг здоровья платформы.\n\n**/admin/health:** endpoint с deploy_status, система метрик, последний деплой.\n\n**Monitoring connections:** подключение внешних источников (PostHog, Stripe, GA4...) → PulseBuilder агрегирует метрики.\n\n**Alert engine:** настраиваемые правила → MonitoringAlert → acknowledgement workflow.\n\n**Diagnostics:** DiagnosisSchedulerJob (weekly Sunday) → DiagnosisJob → AI-анализ аномалий → отчёт.\n\n**KG Health:** KgHealthCheckJob (monthly) — orphan nodes, broken edges, LLM quality sampling, TG alerts.',
    lightBody: 'Автоматические проверки здоровья системы. Статус деплоя. Алерты с подтверждением. Еженедельная AI-диагностика.',
    howItWorks: '/admin/health → deploy_status, metrics. MonitoringSchedulerJob (6h) → SyncJob → PulseBuilder. AlertEngine → rules → MonitoringAlert (acknowledge). DiagnosisJob (weekly) → AI analysis. KgHealthCheckJob (monthly).',
    lightHowItWorks: 'Проверка здоровья → синхронизация метрик → алерты → AI-диагностика.',
    related: ['product-health-monitor', 'admin-command-center', 'tokenomics-guard'],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getRelatedProducts(slugs: string[]): Product[] {
  return slugs.map(s => products.find(p => p.slug === s)).filter(Boolean) as Product[];
}

export function getProductsByGroup(group: Product['group']): Product[] {
  return products.filter(p => p.group === group);
}
