const PRODUCT_COUNT = 39;

const t = {
  meta: {
    title: 'Роман Неверов — AI Product Builder',
    description: `${PRODUCT_COUNT} AI-продуктов в продакшене. Выручка \u00D72.2. 150 человек \u2192 solo + AI. Factory OS.`,
  },
  hero: {
    // Dark theme (tech)
    line1: '> 10 лет руководил продуктами. Теперь строю их с AI.',
    line2: `> ${PRODUCT_COUNT} продуктов в проде. Выручка \u00D72.2. Команда из 150 \u2192 solo + 15 AI-агентов.`,
    line3: '> Ниже \u2014 каждый продукт, каждая подсистема, каждая технология.',
    longText: `Руководил 150 людьми, 11 командами, P&L на сотни миллионов. Вырастил выручку \u00D72.2 при падении рынка на 37%. Потом понял: один человек с правильной AI-архитектурой делает больше, чем отдел.\n\nПостроил Factory OS \u2014 систему из 15 AI-агентов (Builder, Quality, DevOps, Discovery, Strategy...), которые пишут код, тестируют, деплоят и чинят баги. Я принимаю решения. Они исполняют.\n\nРезультат: ${PRODUCT_COUNT} продуктов в продакшене. Флагман \u2014 AICPO (aicpo.ru): платформа из 31 подсистемы для продуктового исследования с AI. Граф знаний, мультимодельный LLM-каскад, self-evolving промпты, competitive intelligence.\n\nВсё что ниже \u2014 доказательство. Не резюме, не обещания. Рабочий код, живые продукты, проверяемые результаты.`,
    // Light theme (business)
    light_line1: '10 лет управлял продуктами и командами. Теперь строю AI-продукты.',
    light_line2: `${PRODUCT_COUNT} продуктов в продакшене. Выручка \u00D72.2 за год. 150 человек \u2192 один + AI.`,
    light_line3: 'Ниже \u2014 портфолио, технологии, статьи. Всё можно проверить.',
    light_longText: `Product Lead в PUNKT E \u2014 крупнейшее EV-приложение в России, 95 000 пользователей. Вырастил выручку в 2.2 раза за год при падении рынка на 37%.\n\nHead of Products в Mafin \u2014 Top-3 insurtech: 11 команд, 150 человек, P&L четырёх направлений, расширение линейки с 3 до 16 продуктов.\n\nСейчас: строю AI-продукты полного цикла \u2014 от исследования рынка до работающего сервиса. ${PRODUCT_COUNT} продуктов в продакшене. Флагман \u2014 AICPO: платформа из 31 подсистемы, которая помогает продуктовым командам принимать решения на данных.\n\nОткрыт к руководству AI-продуктами, консалтингу и корпоративному внедрению AI.`,
  },
  nav: {
    products: 'Продукты',
    stack: 'Стек',
    blog: 'Блог',
    about: 'Обо мне',
    contact: 'Контакты',
    modules: 'Модули',
    docs: 'Docs',
    pricing: 'Тарифы',
    dashboard: 'Dashboard',
  },
  sections: {
    products: '## Продукты',
    latest: '## Последнее',
    newsletter: '## Рассылка',
  },
  products: {
    title: 'Продукты \u2014 Роман Неверов',
    description: `${PRODUCT_COUNT} AI-продуктов, построенных в одиночку с AI-агентами.`,
    subtitle: `${PRODUCT_COUNT} продуктов. Все построены с Claude Code и собственной фабрикой агентов.`,
    light_subtitle: `${PRODUCT_COUNT} продуктов. Все созданы одним человеком с помощью AI-агентов.`,
    viewAll: 'Все продукты \u2192',
    taglines: {
      // --- Standalone products ---
      coffeebot: 'AI-квиз по подбору кофе',
      coffeebotLong: 'AI-квиз по подбору кофе. 8 вопросов \u2192 персональная рекомендация из 100+ сортов.',
      inkcloak: 'Детектор и гуманизатор AI-текста',
      inkcloakLong: 'Детектор AI-текста на fine-tuned DeBERTa (AUROC 0.9948) + гуманизатор через adversarial paraphrasing. GPU-инференс на RunPod.',
      aicpo: 'AI-платформа для продуктового исследования',
      aicpoLong: 'Чат с AI \u2192 извлечение фактов \u2192 генерация 43 стратегических артефактов. Rails 8, мультимодельный LLM-каскад.',
      scrutly: 'Бесплатный детектор AI-текста',
      scrutlyLong: 'Бесплатный детектор AI-текста. Быстро, просто, без регистрации.',
      toolsites: '199 SEO-страниц на 5 доменах',
      toolsitesLong: '199 программатических SEO-страниц. AI-генерация контента с ручной редактурой.',
      openclaw: 'AI-фабрика финансовых агентов',
      openclawLong: '5 специализированных агентов для финансового анализа и отчётности. DeepSeek R1, Docker.',
      rackcloud: 'Своя облачная платформа из 400+ серверов',
      rackcloudLong: 'Архитектура IaaS-провайдера: 400+ bare-metal серверов, 17 сервисов, биллинг, дашборд. Альтернатива Hetzner/DO.',
      diycalc: 'Калькуляторы стройматериалов',
      diycalcLong: 'Бесплатные калькуляторы для бетона, плитки, краски \u2014 с расчётом количества и стоимости.',
      fitcalc: 'Фитнес-калькуляторы',
      fitcalcLong: 'TDEE, ИМТ, процент жира, макросы \u2014 научные формулы с персональными рекомендациями.',

      // --- Light theme standalone ---
      light_coffeebot: 'AI подбирает кофе по вкусовым предпочтениям',
      light_coffeebotLong: 'Пользователь отвечает на 8 вопросов \u2014 AI рекомендует кофе из 100+ сортов. Монетизация через партнёрскую программу.',
      light_inkcloak: 'Определяет AI-текст с точностью 99.5%',
      light_inkcloakLong: 'Нейросеть определяет, написан ли текст искусственным интеллектом. Точность 99.5%. Плюс переписывание текста так, чтобы он читался естественно.',
      light_aicpo: 'AI-помощник для продуктового исследования',
      light_aicpoLong: 'Чат с AI, который помогает исследовать рынок: задаёт вопросы, извлекает факты, генерирует 43 стратегических документа.',
      light_scrutly: 'Бесплатная проверка текста на AI',
      light_scrutlyLong: 'Бесплатная проверка текста на AI. Без регистрации, результат за секунды.',
      light_toolsites: '199 нишевых инструментов для SEO-трафика',
      light_toolsitesLong: '199 страниц с онлайн-калькуляторами и инструментами. Программатический SEO: один шаблон \u2192 сотни страниц.',
      light_openclaw: 'AI-агенты для финансовой аналитики',
      light_openclawLong: '5 агентов: анализ отчётности, прогнозирование, портфели, риски, отчёты. Каждый со своей специализацией.',
      light_rackcloud: 'Проект облачной платформы на 400+ серверов',
      light_rackcloudLong: 'Спроектировал архитектуру IaaS-провайдера: 400+ серверов, 17 сервисов, биллинг, дашборд.',
      light_diycalc: 'Калькуляторы стройматериалов',
      light_diycalcLong: 'Сколько бетона на фундамент? Сколько плитки на ванную? 30+ калькуляторов с расчётом стоимости.',
      light_fitcalc: 'Калькуляторы здоровья и фитнеса',
      light_fitcalcLong: 'Калории, ИМТ, процент жира, макросы \u2014 40+ калькуляторов на основе научных формул.',

      // --- AICPO subsystems (dark = tech) ---
      aicpo_platform: 'AI-воркспейс для продуктового исследования. 16 систем, 43 артефакта',
      aicpo_platformLong: 'Чат с AI \u2192 извлечение фактов \u2192 генерация 43 стратегических артефактов. Rails 8, мультимодельный LLM-каскад, 3-панельный workspace.',
      llm_runtime: '7 уровней отказоустойчивости, авто-калибровка модели, 0 downtime',
      llm_runtimeLong: 'Динамическое обнаружение моделей каждые 12ч. Каскад Groq\u2192OpenRouter\u2192Bootstrap. Авто-blacklist мёртвых моделей. Эскалация при фрустрации. Бюджет-гейт $5/день. 2K токенов вместо 25K на запрос.',
      discovery: 'Автономный рисерч: поиск \u2192 TG-каналы \u2192 статьи \u2192 LLM-фильтрация',
      discoveryLong: '3 раунда исследования. DuckDuckGo + валидация TG-каналов (подписчики \u226550, свежесть <90д). Извлечение статей (vc.ru, Habr). LLM фильтрует только релевантные инсайты. Кеш 90 дней.',
      dual_brain: 'Быстрый мозг для простого, умный \u2014 для сложного. Переключается сам',
      dual_brainLong: 'Groq (0.5с ответ) для стандартных запросов. Детектор фрустрации (5 триггеров: негативный тон, стагнация, повторы) \u2192 авто-эскалация на Claude. Де-эскалация когда разговор нормализуется. Экономия 90% токенов.',
      artifact_pipeline: 'Трёхступенчатая генерация: Structure \u2192 Generate \u2192 Validate \u2192 retry',
      artifact_pipelineLong: '43 типа стратегических артефактов. Pipeline: Groq строит структуру \u2192 Gemini генерирует \u2192 Groq валидирует. Авто-retry при score <0.5. A/B тест моделей через ?model= параметр.',
      semantic_memory: 'Векторный поиск по смыслу + автотрекинг 19 AJTBD data points',
      semantic_memoryLong: 'pg_vector embeddings + cosine similarity. Факты ищутся по смыслу, не по ключевым словам. Авто-отслеживание покрытия 19 AJTBD data points. Project brief (~300 токенов) вместо полной истории.',
      health_monitor: 'Живой пульс продукта: 46 интеграций, 6 коннекторов live, 28 в roadmap',
      health_monitorLong: '46 интеграций (12 готовых, 8 адаптеров, 26 запланированных). 28 коннекторов мониторинга: PostHog, Stripe, GA4, Яндекс Метрика, ЮKassa, CloudPayments (live) + Mixpanel, Sentry, Intercom, Amplitude, HubSpot, AmoCRM и ещё 16. Real-time пульс, alert rules, ActionCable push.',
      team_os: 'Организации, RBAC, SSO (SAML + OIDC), аудит-лог',
      team_osLong: '4 роли (owner/admin/editor/viewer). SAML 2.0 + OIDC с auto-provisioning. Immutable audit log. Threaded комментарии с @AI \u2014 бот отвечает в треде. Artifact tasks (collect/analyze/review).',
      self_evolving: 'Промпты улучшают себя сами из негативного фидбека',
      self_evolvingLong: 'Еженедельный auto-draft улучшений. Версионирование промптов с performance snapshots. Feedback digest каждые 24ч. Система буквально учится на ошибках.',
      evolution: 'AI генерирует бэклог из фидбека и чат-аудита',
      evolutionLong: 'Feedback \u2192 Digest (ежедневно) \u2192 AI Analysis (еженедельно, Claude Sonnet) \u2192 Backlog с приоритетами. Chat Audit (Groq анализирует сессии). Пользователи голосуют за custom artifacts, vote \u22653 \u2192 промоушен.',
      research_corpus: 'Shared база знаний: один рисерч \u2014 данные для всех',
      research_corpusLong: 'Ниши \u2192 каналы \u2192 посты \u2192 статьи \u2192 инсайты. SHA256 дедупликация. TTL: посты 24ч, статьи 7д, инсайты 90д. Один раз исследовал нишу \u2014 все пользователи получают данные бесплатно.',
      pain_extractor: 'Парсер чат-экспортов \u2192 19 AJTBD data points',
      pain_extractorLong: 'Отдельный Rails engine. Загрузка экспортов из TG, Discord, Slack, WhatsApp \u2192 деперсонализация \u2192 LLM извлекает 19 структурированных полей \u2192 JSON.',
      credit_engine: 'Атомарные транзакции с row lock \u2014 race condition невозможен',
      credit_engineLong: '6 тиеров (free \u2192 enterprise). Soft limits с овердрафтом для бизнеса. Idempotency keys. BYOK (Bring Your Own Key) для OpenRouter. Usage % в статусбаре.',
      tokenomics: 'Трекинг стоимости каждого LLM-запроса, бюджет-гейт',
      tokenomicsLong: 'Каждый LLM-запрос: model, input/output tokens, estimated cost \u2192 workspace_llm_usages. Дневной лимит $5. Алерт на 80%. Premium модели блокируются при превышении.',
      email_bridge: 'Двусторонний email-канал: IMAP poll \u2192 маршрутизация в проекты',
      email_bridgeLong: 'IMAP poll каждые 2 минуты. SMTP отправка приглашений и артефактов. Маршрутизация по In-Reply-To \u2192 subject tag \u2192 EmailChannel \u2192 User. Защита от auto-reply и bounce.',
      pdf_publisher: 'Публичные PDF с цифровой подписью: document ID + замороженный контент + верификация',
      pdf_publisherLong: 'Каждый документ получает уникальный ID (AICPO-YYYYMM-HEXHEX). Контент замораживается на момент создания \u2014 изменить невозможно. По ID можно верифицировать подлинность. Print-ready B4, watermark, счётчик просмотров, публичный доступ без логина.',
      vector_intelligence: '4-уровневая модель данных: текст \u2192 факты \u2192 векторы \u2192 граф',
      vector_intelligenceLong: 'Сырые сообщения \u2192 LLM extraction \u2192 структурированные факты (5 измерений, веса 10-100) \u2192 pg_vector embeddings + cosine similarity \u2192 Knowledge Graph. Каждый уровень обогащает предыдущий. SQLite fallback для dev.',
      knowledge_graph: 'Графовое хранилище: 14 типов нод, evidence trail до слов пользователя',
      knowledge_graphLong: 'Отдельный Rails engine. 14 типов нод: pain, job, segment, competitor, feature, trend, metric, constraint, person, channel, solution, trigger, emotion, criteria. Edges с confidence. Полная трассируемость: рекомендация \u2192 факт \u2192 сообщение пользователя.',
      admin_dashboard: 'Командный центр: KPI, CRM, аналитика, Ship pipeline, TG-канал, инвайты',
      admin_dashboardLong: 'Full-page KPI дашборд: фильтруемая таблица, detail panel, bulk actions, keyboard shortcuts. Единый командный центр для всех операций платформы.',
      crm_engine: 'CRM: lead scoring, churn detector, reactivation, referral',
      crm_engineLong: 'AI lead scoring (daily cron). Churn detector с автоматическими reactivation emails. Referral система (5000 credits за активацию). 28 засеянных кампаний. Session briefing для персонализации.',
      marketing_analytics: 'Воронка, когорты, кампании, UTM-трекинг',
      marketing_analyticsLong: 'Полная маркетинговая аналитика: воронка конверсии, когортный анализ, 28 кампаний с UTM-трекингом. Интеграция с GA4 и PostHog. Еженедельные отчёты (cron).',
      ship_pipeline: 'Голосование \u2192 promote \u2192 auto-generate \u2192 notify. Продукт развивает сам себя',
      ship_pipelineLong: 'Пользователи запрашивают custom артефакты \u2192 другие голосуют \u2192 vote \u22653 \u2192 кандидат на промоушен \u2192 admin нажимает Ship \u2192 автогенерация через LLM \u2192 уведомление через ActionCable. Самоуправляемый бэклог.',
      tg_publisher: 'Публикация контента в TG-канал из платформы',
      tg_publisherLong: 'Управление TG-каналом из админки. Cloudflare Worker relay для доставки. Форматирование, предпросмотр, отложенная публикация.',
      blog_publisher: 'Блог-система с публикацией из платформы',
      blog_publisherLong: 'Создание и управление блог-постами. Markdown + превью. SEO-оптимизация. Публикация из админ-панели.',
      incident_pipeline: 'Эскалация инцидентов \u2192 фичи. AI-управление бэклогом',
      incident_pipelineLong: 'DevBugfixLogger (8 категорий) \u2192 evolution_backlog. Негативный фидбек \u2192 AI анализ (Claude Sonnet weekly) \u2192 приоритизированный бэклог. Chat audit (Groq weekly) \u2192 паттерны \u2192 бэклог. Инцидент автоматически становится фичей.',
      pnl_economics: 'P&L и unit economics платформы',
      pnl_economicsLong: 'Кредитная система: 6 тиеров, welcome bonus, atomic deductions. Ежемесячные лимиты (free=100, enterprise=300K). Soft limits с овердрафтом. Per-member usage analytics. Transaction history. Usage % в statusbar.',
      quality_management: 'Управление качеством: фидбек \u2192 улучшение \u2192 версионирование',
      quality_managementLong: 'Thumbs per dimension (Accuracy/Completeness/Relevance). Feedback digest (daily). Prompt improvement (weekly auto-draft). Artifact staleness detection (facts_hash + prompt_hash). Версионирование промптов с performance snapshots.',
      system_health: 'Здоровье системы: health check, deploy status, мониторинг',
      system_healthLong: '/admin/health endpoint с deploy_status. Monitoring connections + pulse builder. Scheduled sync jobs. Alert engine с acknowledgement. Диагностика (weekly cron).',
      user_management: 'Управление пользователями: инвайты, тиеры, анонимная воронка',
      user_managementLong: 'Beta invites (8-char коды). 3 тиера (free/beta/admin). Anonymous lockdown: 3 бесплатных сообщения \u2192 регистрация. Shadow projects с claim. IP rate limit (10 проектов/день). Welcome bonus при регистрации.',
      competitive_intel: 'Мониторинг конкурентов: авто-скрейпинг, сигналы, дайджест',
      competitive_intelLong: 'Автодетекция конкурентов из чат-фактов. Web scrape каждые 6ч + DuckDuckGo news. Сигналы: relevance scoring (Groq), threat mapping, KG-интеграция (competitor/feature nodes). Еженедельный дайджест. Critical сигналы \u2192 artifact staleness.',
      trend_monitor: 'Мониторинг трендов: DuckDuckGo \u2192 кластеризация \u2192 KG \u2192 3 артефакта',
      trend_monitorLong: 'Еженедельный мониторинг трендов по нишам. Jaccard similarity кластеризация. LLM scoring niche relevance. KG: trend nodes + addresses/enables edges. 3 артефакта: trend_radar, opportunity_map, roadmap_recommendations.',

      // --- Light theme AICPO subsystems (business language) ---
      light_aicpo_platform: 'AI-помощник для продуктовых исследований. 16 систем, 43 документа',
      light_aicpo_platformLong: 'Чат с AI, который исследует рынок, извлекает инсайты и генерирует 43 стратегических документа \u2014 от карты конкурентов до финансовой модели.',
      light_llm_runtime: 'Умный роутинг между AI-моделями: автовыбор лучшей по скорости и цене',
      light_llm_runtimeLong: 'Система автоматически выбирает AI-модель для каждого запроса. 7 уровней подстраховки \u2014 если одна модель упала, подключается следующая. Контроль бюджета: лимит расходов в день.',
      light_discovery: 'Автоматическое исследование рынка: каналы, статьи, инсайты по нише',
      light_discoveryLong: 'AI сам находит релевантные TG-каналы, статьи на vc.ru и Habr, фильтрует только полезное. Три раунда углубления. Результаты кешируются \u2014 повторный запрос бесплатен.',
      light_dual_brain: 'Быстрый мозг для простого, умный \u2014 для сложного. Переключается сам',
      light_dual_brainLong: 'Простые вопросы \u2014 мгновенный ответ (0.5 секунды). Сложная ситуация или фрустрация \u2014 автоматическое подключение продвинутой модели. Экономия 90% на AI без потери качества.',
      light_artifact_pipeline: '43 стратегических документа: от JTBD-карт до финансовых моделей',
      light_artifact_pipelineLong: '43 типа документов. Каждый проходит три этапа: структурирование, генерация, проверка качества. Если качество ниже порога \u2014 автоматическая переделка.',
      light_semantic_memory: 'Платформа помнит всё: поиск по смыслу, а не по ключевым словам',
      light_semantic_memoryLong: 'Все факты из разговоров сохраняются и ищутся по смыслу. Автоматический трекинг: какие данные о проекте уже есть, каких не хватает.',
      light_health_monitor: 'Мониторинг бизнес-метрик: PostHog, Stripe, GA4, Метрика \u2014 в одном дашборде',
      light_health_monitorLong: '46 интеграций с аналитическими сервисами. Живой пульс продукта: выручка, трафик, конверсии, алерты \u2014 всё в одном месте.',
      light_team_os: 'Командная работа: роли, SSO-авторизация, аудит действий',
      light_team_osLong: 'Организации с ролями (владелец, админ, редактор, зритель). Корпоративная авторизация через SAML/OIDC. Аудит-лог всех действий. Комментарии к документам с @AI \u2014 бот отвечает в треде.',
      light_self_evolving: 'Система учится на ошибках: AI автоматически улучшает качество ответов',
      light_self_evolvingLong: 'Каждую неделю AI анализирует негативные отзывы и предлагает улучшения промптов. Версионирование с замерами качества \u2014 можно откатить если стало хуже.',
      light_evolution: 'Автоматический roadmap: AI анализирует фидбек и приоритизирует улучшения',
      light_evolutionLong: 'Отзывы пользователей \u2192 ежедневная сводка \u2192 AI-анализ каждую неделю \u2192 приоритизированный план улучшений. Пользователи голосуют за нужные фичи.',
      light_research_corpus: 'Общая база исследований: один раз изучил нишу \u2014 данные доступны всем',
      light_research_corpusLong: 'Результаты исследований сохраняются в общую базу. Если кто-то уже изучал похожую нишу \u2014 данные доступны сразу, без повторного поиска.',
      light_pain_extractor: 'Извлечение инсайтов из переписок: загрузи чат \u2192 получи структурированный анализ',
      light_pain_extractorLong: 'Загрузите экспорт чата из Telegram, Slack, Discord или WhatsApp. AI извлечёт ключевые данные: боли, задачи, сегменты, триггеры покупки.',
      light_credit_engine: 'Биллинг и тарификация: 6 тарифов, прозрачный расход, защита от перерасхода',
      light_credit_engineLong: '6 тарифных планов от бесплатного до enterprise. Прозрачный расход: каждое действие имеет стоимость в кредитах. Бизнес-планы допускают перерасход с последующим счётом.',
      light_tokenomics: 'Контроль расходов на AI: лимит в день, алерт при приближении к потолку',
      light_tokenomicsLong: 'Каждый AI-запрос учитывается: модель, объём, стоимость. Дневной лимит бюджета. Алерт на 80% расхода. Дорогие модели автоматически блокируются при превышении.',
      light_email_bridge: 'Email-интеграция: получай и отправляй письма прямо из платформы',
      light_email_bridgeLong: 'Двусторонний email-канал. Отправка приглашений и документов. Входящие письма автоматически попадают в нужный проект.',
      light_pdf_publisher: 'Публикация документов: PDF с подписью, верификация подлинности, публичные ссылки',
      light_pdf_publisherLong: 'Каждый документ получает уникальный ID. Контент замораживается \u2014 изменить невозможно. Можно верифицировать подлинность по ID. Публичный доступ без логина.',
      light_vector_intelligence: 'Многоуровневый анализ: от сырого текста до графа знаний автоматически',
      light_vector_intelligenceLong: 'Четыре уровня обработки: сырой текст \u2192 структурированные факты \u2192 векторные связи \u2192 граф знаний. Каждый уровень обогащает предыдущий.',
      light_knowledge_graph: 'Граф знаний: связи между фактами, трассировка до слов клиента',
      light_knowledge_graphLong: '14 типов объектов: боли, задачи, сегменты, конкуренты, тренды. Все связи между ними. Полная трассируемость: любая рекомендация \u2014 до конкретных слов пользователя.',
      light_admin_dashboard: 'Командный центр: KPI, CRM, аналитика \u2014 всё в одном',
      light_admin_dashboardLong: 'Единый дашборд для управления платформой: метрики, пользователи, контент, инвайты, публикации.',
      light_crm_engine: 'CRM: скоринг лидов, определение оттока, реактивация, реферальная программа',
      light_crm_engineLong: 'AI оценивает лидов ежедневно. Автоматическое определение оттока + реактивационные email. Реферальная программа: бонус за каждого приведённого пользователя.',
      light_marketing_analytics: 'Воронка, когорты, кампании, UTM-трекинг',
      light_marketing_analyticsLong: 'Полная маркетинговая аналитика: воронка конверсии, когортный анализ, 28 кампаний с UTM-трекингом. Интеграция с GA4 и PostHog.',
      light_ship_pipeline: 'Пользователи голосуют за фичи \u2192 AI генерирует \u2192 продукт развивается сам',
      light_ship_pipelineLong: 'Пользователи запрашивают документы \u2192 другие голосуют \u2192 набрал 3+ голоса \u2192 AI генерирует автоматически \u2192 уведомление всем заинтересованным.',
      light_tg_publisher: 'Публикация в Telegram-канал из платформы',
      light_tg_publisherLong: 'Управление Telegram-каналом из админки: создание постов, предпросмотр, публикация.',
      light_blog_publisher: 'Блог-система с публикацией из платформы',
      light_blog_publisherLong: 'Создание и публикация статей. Markdown, SEO-оптимизация, предпросмотр.',
      light_incident_pipeline: 'Баг \u2192 анализ \u2192 фича: AI превращает инциденты в улучшения',
      light_incident_pipelineLong: 'Каждый баг и негативный отзыв автоматически анализируется AI. Результат \u2014 приоритизированный план улучшений. Инциденты превращаются в фичи.',
      light_pnl_economics: 'P&L и юнит-экономика платформы',
      light_pnl_economicsLong: 'Кредитная система: 6 тарифов, прозрачная экономика. Лимиты по тарифам, аналитика расхода по пользователям, история транзакций.',
      light_quality_management: 'Управление качеством: отзывы \u2192 улучшение \u2192 версионирование',
      light_quality_managementLong: 'Оценка по трём параметрам: точность, полнота, релевантность. Ежедневная сводка отзывов. Еженедельное автоулучшение промптов. Детекция устаревших документов.',
      light_system_health: 'Мониторинг здоровья системы: проверки, статус, алерты',
      light_system_healthLong: 'Автоматические проверки здоровья. Статус деплоя. Синхронизация данных. Алерты с подтверждением. Еженедельная диагностика.',
      light_user_management: 'Управление пользователями: инвайты, тарифы, регистрация',
      light_user_managementLong: 'Инвайт-коды, три тарифа. Анонимные пользователи получают 3 бесплатных сообщения \u2014 затем регистрация. Бонус кредитов при регистрации.',
      light_competitive_intel: 'Мониторинг конкурентов: автоматическое отслеживание изменений и угроз',
      light_competitive_intelLong: 'Система сама находит конкурентов из данных проекта. Отслеживает их сайты и новости каждые 6 часов. Оценивает угрозы, формирует еженедельный дайджест.',
      light_trend_monitor: 'Мониторинг трендов в нише: автоматический поиск и оценка влияния',
      light_trend_monitorLong: 'Еженедельный поиск трендов по нише проекта. Кластеризация похожих сигналов. Оценка релевантности для бизнеса. Три аналитических документа: радар трендов, карта возможностей, рекомендации для roadmap.',
    },
    metrics: {
      coffeebot: '82 кофейных профиля сгенерировано',
      inkcloak: 'AUROC 0.9948 точность детекции',
      aicpo: '43 артефакта на базе Product DNA',
      toolsites: '199 страниц на 5 доменах',
      openclaw: '5 агентов, задеплоено на 2 машинах',
      rackcloud: '17 IaaS-сервисов, 400+ серверов, 10 стоек',
      diycalc: '30+ калькуляторов',
      fitcalc: '40+ калькуляторов',
      aicpo_platform: '43 артефакта, 16 систем',
      llm_runtime: '7 уровней fallback, 0 downtime',
      discovery: '3 раунда, кеш 90 дней',
      dual_brain: '5 триггеров, 0.5с \u2192 Claude',
      artifact_pipeline: '43 типа, 3 стадии',
      semantic_memory: '19 data points, vector search',
      health_monitor: '46 интеграций, 28 коннекторов',
      team_os: 'SAML + OIDC, 4 роли',
      self_evolving: 'авто-draft еженедельно',
      evolution: 'Feedback \u2192 AI \u2192 Backlog',
      research_corpus: 'cross-user, TTL 90д',
      pain_extractor: '4 мессенджера \u2192 19 полей',
      credit_engine: '6 тиеров, row locks',
      tokenomics: '$5/день, алерт 80%',
      email_bridge: 'poll 2 мин, auto-routing',
      pdf_publisher: 'B4, watermark, public links',
      vector_intelligence: '4 уровня, pg_vector, 5 измерений',
      knowledge_graph: '14 типов нод, edges, evidence trail',
      admin_dashboard: 'KPI, bulk actions, hotkeys',
      crm_engine: 'lead scoring, churn, referral',
      marketing_analytics: 'воронка, когорты, 28 кампаний',
      ship_pipeline: 'vote \u2192 promote \u2192 auto-generate',
      tg_publisher: 'CF Worker relay, TG канал',
      blog_publisher: 'markdown, SEO, превью',
      incident_pipeline: 'инцидент \u2192 AI анализ \u2192 фича',
      pnl_economics: '6 тиеров, soft limits, P&L',
      quality_management: '3 dimension feedback, auto-draft',
      system_health: 'health check, deploy status',
      user_management: 'инвайты, 3 тиера, shadow projects',
      competitive_intel: 'авто-скрейпинг 6ч, KG-интеграция',
      trend_monitor: 'weekly scan, 3 артефакта',
      // Light theme metrics (business language)
      light_coffeebot: '82 рекомендации, 100+ сортов',
      light_inkcloak: 'точность 99.5%, GPT/Claude/Gemini',
      light_aicpo: '43 документа, исследование за минуты',
      light_toolsites: '199 страниц, 5 сайтов',
      light_openclaw: '5 агентов, автоматические отчёты',
      light_rackcloud: '400+ серверов, 17 сервисов',
      light_diycalc: '30+ калькуляторов',
      light_fitcalc: '40+ калькуляторов',
      light_aicpo_platform: '43 документа, 16 систем',
      light_llm_runtime: 'автовыбор модели, контроль бюджета',
      light_discovery: 'автоматический рисерч за минуты',
      light_dual_brain: 'быстрый + умный, экономия 90%',
      light_artifact_pipeline: '43 документа с проверкой качества',
      light_semantic_memory: 'поиск по смыслу, трекинг данных',
      light_health_monitor: '46 интеграций, живой дашборд',
      light_team_os: 'роли, SSO, аудит',
      light_self_evolving: 'самообучение из отзывов',
      light_evolution: 'AI-приоритизация улучшений',
      light_research_corpus: 'общая база, без повторных поисков',
      light_pain_extractor: '4 мессенджера, автоанализ',
      light_credit_engine: '6 тарифов, прозрачный расход',
      light_tokenomics: 'контроль бюджета на AI',
      light_email_bridge: 'входящие + исходящие, авторутинг',
      light_pdf_publisher: 'PDF с подписью, верификация',
      light_vector_intelligence: '4 уровня обработки данных',
      light_knowledge_graph: '14 типов объектов, трассируемость',
      light_admin_dashboard: 'единый дашборд управления',
      light_crm_engine: 'скоринг, отток, реферальная программа',
      light_marketing_analytics: 'воронка, когорты, кампании',
      light_ship_pipeline: 'голосование \u2192 автогенерация',
      light_tg_publisher: 'публикация из админки',
      light_blog_publisher: 'статьи, SEO, превью',
      light_incident_pipeline: 'баг \u2192 AI-анализ \u2192 улучшение',
      light_pnl_economics: '6 тарифов, аналитика расхода',
      light_quality_management: '3 параметра, автоулучшение',
      light_system_health: 'мониторинг, алерты, диагностика',
      light_user_management: 'инвайты, тарифы, регистрация',
      light_competitive_intel: 'автомониторинг конкурентов',
      light_trend_monitor: 'еженедельный поиск трендов',
    },
  },
  stack: {
    title: 'Стек за $15/мес \u2014 Роман Неверов',
    description: `Как я запускаю ${PRODUCT_COUNT} AI-продуктов на $15/мес инфраструктуры.`,
    heading: '## Стек за $15/мес',
    subtitle: `Всё, что нужно для ${PRODUCT_COUNT} AI-продуктов. Общая стоимость: $15/мес.`,
    headers: {
      service: 'Сервис',
      cost: 'Стоимость',
      what: 'Что делает',
      limit: 'Бесплатный лимит',
    },
    savedHeading: '## Сэкономлено',
    savedSubtitle: 'Эквивалентные платные сервисы:',
    savedHeaders: {
      wouldPay: 'Платил бы за',
      cost: 'Стоимость',
      using: 'Использую вместо',
    },
    totalSavings: 'Ежемесячная экономия',
  },
  about: {
    title: 'Обо мне \u2014 Роман Неверов',
    description: `Руководитель AI-продуктов. 10+ лет в product management. ${PRODUCT_COUNT} AI-продуктов в продакшене.`,
    heading: '## Обо мне',
    // --- Dark theme (tech) ---
    bio1: 'Роман Неверов. Москва.',
    bio2: '<strong>Руководитель AI-продуктов</strong> с инженерным бэкграундом. Редкое сочетание: 10 лет продуктового управления (команды до 150 человек, P&L, M&A) + hands-on AI/ML (PyTorch, LoRA fine-tuning, LLM-оркестрация, GPU-деплой).',
    bio3: '<strong>AICPO</strong> (<a href="https://aicpo.ru">aicpo.ru</a>) \u2014 мой флагманский продукт. SaaS-платформа для продуктовых исследований: 31 подсистема, 43 артефакта, мультимодельный LLM-каскад (Groq \u2192 OpenRouter \u2192 Claude), Knowledge Graph, SSO (SAML + OIDC), CRM, мониторинг. Rails 8, PostgreSQL, Docker. Живой продукт в продакшене.',
    bio4: '<strong>PUNKT E</strong> (2024\u20132026) \u2014 Product Lead. Крупнейшее EV-приложение в РФ, 95K пользователей. Выручка \u00D72.2 за год при падении рынка на 37%. NPS: 3.2 \u2192 4.9. Запустил AI-проекты: предсказание зарядных сессий (PyTorch), прототип чатбота поддержки (LLM), AI-исследование рынка.',
    bio5: '<strong>Mafin</strong> (2022\u20132024) \u2014 Head of Products. Top-3 insurtech. 11 команд, 150 человек. P&L 4 бизнес-линий. Расширил линейку с 3 до 16 продуктов. 70+ партнёрских интеграций. M&A интеграция двух компаний.',
    bio6: `<strong>Factory OS</strong> \u2014 технология управления AI-агентами. 15 ролей (Builder, Quality, DevOps, Discovery, Strategy...), 40+ правил, quality gates. Все ${PRODUCT_COUNT} продуктов построены через неё. Воспроизводимая методология \u2014 <a href="/methodology">подробнее</a>.`,
    // --- Light theme (business) ---
    light_bio1: 'Роман Неверов. Москва.',
    light_bio2: '<strong>Руководитель AI-продуктов.</strong> 10 лет управлял продуктами и командами до 150 человек. Последние 2 года \u2014 строю AI-продукты полного цикла: от исследования рынка до работающего сервиса.',
    light_bio3: '<strong>Флагман \u2014 <a href="https://aicpo.ru">AICPO</a></strong>. Платформа, которая помогает продуктовым командам исследовать рынок с помощью AI. 31 подсистема: от интеллектуального чата до графа знаний и мониторинга бизнес-метрик. Живой продукт, можно попробовать.',
    light_bio4: '<strong>PUNKT E</strong> (2024\u20132026). Руководил продуктом крупнейшего EV-приложения в России (95 000 пользователей). Вырастил выручку в 2.2 раза за год \u2014 при том, что рынок упал на 37%. Поднял NPS с 3.2 до 4.9. Запустил три AI-проекта внутри компании.',
    light_bio5: '<strong>Mafin</strong> (2022\u20132024). Возглавлял продуктовое подразделение Top-3 insurtech: 11 команд, 150 человек, P&L четырёх бизнес-линий. Расширил линейку с 3 до 16 продуктов. Провёл M&A-интеграцию.',
    light_bio6: `<strong>Сейчас:</strong> ${PRODUCT_COUNT} AI-продуктов в продакшене. Создаю их с помощью собственной системы AI-агентов (Factory OS) \u2014 15 специализированных ролей, от разработчика до маркетолога. Открыт к сотрудничеству.`,
    linksHeading: '## Ссылки',
    resumeLabel: 'Резюме (PDF)',
    emailLabel: 'Для предложений',
    tgLabel: 'Telegram',
    githubLabel: 'GitHub',
    nowHeading: '## Чем могу быть полезен',
    now1: 'Руководство AI-продуктами \u2014 от стратегии и discovery до архитектуры и деплоя',
    now2: 'Построение AI-пайплайнов \u2014 LLM-оркестрация, мультимодельные каскады, агентные системы',
    now3: 'AI-аудит продукта \u2014 где AI даст максимальный ROI в вашем бизнесе',
  },
  contact: {
    title: 'Контакты \u2014 Роман Неверов',
    description: 'Открыт к предложениям и сотрудничеству. Email, Telegram.',
    heading: '## Контакты',
    subtitle: 'Открыт к предложениям и сотрудничеству',
    offersHeading: '## Чем могу быть полезен',
    offer1: 'Руководитель AI-продукта \u2014 полный цикл от стратегии до деплоя',
    offer2: 'AI-консалтинг \u2014 аудит продукта, построение AI-пайплайнов',
    offer3: 'Разработка AI-продуктов \u2014 от MVP до продакшена за недели',
  },
  newsletter: {
    title: 'Рассылка \u2014 Роман Неверов',
    description: 'Следите за проектами. Одно письмо когда выходит новый продукт.',
    heading: '## Рассылка',
    followBuild: 'Следите за проектами',
    followDesc: 'Одно письмо когда выходит новый продукт, важное обновление или статья. Без спама, без growth-хаков.',
    unsubscribe: 'Отписаться можно в любой момент.',
    formTitle: 'Следите за проектами',
    formSubtitle: 'Одно письмо когда выходит новый продукт. Без спама.',
    placeholder: 'ваш@email.ru',
    button: 'Подписаться',
    success: 'Подписка оформлена! Проверьте почту.',
    previousTopics: 'Предыдущие темы:',
    topic1: `> ${PRODUCT_COUNT} AI-продуктов за месяц`,
    topic2: '> Стек за $15/мес',
    topic3: '> Factory OS: фабрика AI-агентов',
  },
  footer: {
    built: 'Роман Неверов',
    based: 'Москва',
  },
  blog: {
    title: 'Блог \u2014 Роман Неверов',
    subtitle: 'Строю в открытую. AI-продукты, стек, карьера.',
    backToBlog: 'Назад в блог',
    readMore: 'Читать',
    minRead: 'мин чтения',
  },
  common: {
    live: 'LIVE',
    launching: 'ЗАПУСК',
    building: 'В РАБОТЕ',
    planned: 'ПЛАН',
    built: 'ГОТОВО',
  },
  // Links (single source of truth)
  links: {
    email: 'nevr@aicpo.com',
    telegram: '@nevrdigital',
    telegramUrl: 'https://t.me/nevrdigital',
    github: 'nevr-ai',
    githubUrl: 'https://github.com/nevr-ai',
  },
};

export default t;
