const PRODUCT_COUNT = 24;

const t = {
  meta: {
    title: 'Роман Неверов — AI Product Builder',
    description: `AI-продукты в одиночку. ${PRODUCT_COUNT} продуктов, $15/мес инфраструктура, Factory OS.`,
  },
  hero: {
    line1: '> Строю AI-продукты. В одиночку.',
    line2: '> 24 продукта. Revenue ×5.7. $15/мес на инфраструктуру.',
    line3: '> Claude Code + собственная AI-фабрика агентов.',
    longText: 'Я строю продукты с помощью AI-агентов. Не в смысле «использую ChatGPT» — настоящие автономные агенты, которые пишут код, запускают тесты, деплоят в продакшн и чинят баги пока я сплю.\n\nМоя система называется Factory OS. Это оркестрация поверх Claude Code с 15 специализированными ролями агентов: Builder, Discovery, Strategy, Quality, DevOps, Marketing и другие. CEO-агент делегирует задачи, Builder-агент пишет код, Quality-агент ревьюит. Я утверждаю коммиты.\n\nДо этого — 10 лет в продуктовом управлении: руководил командой из 150 человек, вырастил revenue с 70M до 396M₽ (×5.7 за 2 года) при падении рынка на 37%. NPS с 3.2 до 4.9.\n\n24 продукта (8 standalone + 16 систем AICPO Platform). Инфраструктура $15/мес. Будущее — за one-person companies, усиленными AI.',
  },
  nav: {
    products: 'Продукты',
    stack: 'Стек',
    blog: 'Блог',
    about: 'Обо мне',
    contact: 'Контакты',
  },
  sections: {
    products: '## Продукты',
    latest: '## Последнее',
    newsletter: '## Рассылка',
  },
  products: {
    title: 'Продукты — Роман Неверов',
    description: `${PRODUCT_COUNT} AI-продуктов, построенных в одиночку с AI-агентами.`,
    subtitle: `${PRODUCT_COUNT} продуктов. Все построены с Claude Code и собственной фабрикой агентов.`,
    viewAll: 'Все продукты \u2192',
    taglines: {
      coffeebot: 'AI-квиз по подбору кофе',
      coffeebotLong: 'AI-квиз по подбору кофе. 8 вопросов → персональная рекомендация из 100+ сортов.',
      inkcloak: 'Детектор и гуманизатор AI-текста',
      inkcloakLong: 'Детектор AI-текста на fine-tuned DeBERTa (AUROC 0.9948) + гуманизатор через adversarial paraphrasing. GPU-инференс на RunPod.',
      aicpo: 'AI-платформа для продуктового исследования',
      aicpoLong: 'Чат с AI → извлечение фактов → генерация 43 стратегических артефактов. Rails 8, мультимодельный LLM-каскад.',
      scrutly: 'Бесплатный детектор AI-текста',
      scrutlyLong: 'Бесплатный детектор AI-текста. Быстро, просто, без регистрации.',
      toolsites: '199 SEO-страниц на 5 доменах',
      toolsitesLong: '199 программатических SEO-страниц. AI-генерация контента с ручной редактурой.',
      openclaw: 'AI-фабрика финансовых агентов',
      openclawLong: '5 специализированных агентов для финансового анализа и отчётности. DeepSeek R1, Docker.',
      rackcloud: 'Своя облачная платформа из 400+ серверов',
      rackcloudLong: 'Архитектура IaaS-провайдера: 400+ bare-metal серверов, 17 сервисов, биллинг, дашборд. Альтернатива Hetzner/DO.',
      diycalc: 'Калькуляторы стройматериалов',
      diycalcLong: 'Бесплатные калькуляторы для бетона, плитки, краски — с расчётом количества и стоимости.',
      fitcalc: 'Фитнес-калькуляторы',
      fitcalcLong: 'TDEE, ИМТ, процент жира, макросы — научные формулы с персональными рекомендациями.',
      aicpo_platform: 'AI-воркспейс для продуктового исследования. 16 систем, 43 артефакта',
      aicpo_platformLong: 'Чат с AI → извлечение фактов → генерация 43 стратегических артефактов. Rails 8, мультимодельный LLM-каскад, 3-панельный workspace.',
      llm_runtime: '7 уровней отказоустойчивости, авто-калибровка модели, 0 downtime',
      llm_runtimeLong: 'Динамическое обнаружение моделей каждые 12ч. Каскад Groq→OpenRouter→Bootstrap. Авто-blacklist мёртвых моделей. Эскалация при фрустрации. Бюджет-гейт $5/день. 2K токенов вместо 25K на запрос.',
      discovery: 'Автономный рисерч: поиск → TG-каналы → статьи → LLM-фильтрация',
      discoveryLong: '3 раунда исследования. DuckDuckGo + валидация TG-каналов (подписчики ≥50, свежесть <90д). Извлечение статей (vc.ru, Habr). LLM фильтрует только релевантные инсайты. Кеш 90 дней.',
      dual_brain: 'Быстрый мозг для простого, умный — для сложного. Переключается сам',
      dual_brainLong: 'Groq (0.5с ответ) для стандартных запросов. Детектор фрустрации (5 триггеров: негативный тон, стагнация, повторы) → авто-эскалация на Claude. Де-эскалация когда разговор нормализуется. Экономия 90% токенов.',
      artifact_pipeline: 'Трёхступенчатая генерация: Structure → Generate → Validate → retry',
      artifact_pipelineLong: '43 типа стратегических артефактов. Pipeline: Groq строит структуру → Gemini генерирует → Groq валидирует. Авто-retry при score <0.5. A/B тест моделей через ?model= параметр.',
      semantic_memory: 'Векторный поиск по смыслу + автотрекинг 19 AJTBD data points',
      semantic_memoryLong: 'pg_vector embeddings + cosine similarity. Факты ищутся по смыслу, не по ключевым словам. Авто-отслеживание покрытия 19 AJTBD data points. Project brief (~300 токенов) вместо полной истории.',
      health_monitor: 'Живой пульс продукта из 6 аналитических источников',
      health_monitorLong: '6 коннекторов: PostHog, Stripe, GA4, Яндекс Метрика, ЮKassa, CloudPayments. Real-time пульс в workspace. Alert rules + ActionCable push. 28 коннекторов в roadmap.',
      team_os: 'Организации, RBAC, SSO (SAML + OIDC), аудит-лог',
      team_osLong: '4 роли (owner/admin/editor/viewer). SAML 2.0 + OIDC с auto-provisioning. Immutable audit log. Threaded комментарии с @AI — бот отвечает в треде. Artifact tasks (collect/analyze/review).',
      self_evolving: 'Промпты улучшают себя сами из негативного фидбека',
      self_evolvingLong: 'Еженедельный auto-draft улучшений. Версионирование промптов с performance snapshots. Feedback digest каждые 24ч. Система буквально учится на ошибках.',
      evolution: 'AI генерирует бэклог из фидбека и чат-аудита',
      evolutionLong: 'Feedback → Digest (ежедневно) → AI Analysis (еженедельно, Claude Sonnet) → Backlog с приоритетами. Chat Audit (Groq анализирует сессии). Пользователи голосуют за custom artifacts, vote ≥3 → промоушен.',
      research_corpus: 'Shared база знаний: один рисерч — данные для всех',
      research_corpusLong: 'Ниши → каналы → посты → статьи → инсайты. SHA256 дедупликация. TTL: посты 24ч, статьи 7д, инсайты 90д. Один раз исследовал нишу — все пользователи получают данные бесплатно.',
      pain_extractor: 'Парсер чат-экспортов → 19 AJTBD data points',
      pain_extractorLong: 'Отдельный Rails engine. Загрузка экспортов из TG, Discord, Slack, WhatsApp → деперсонализация → LLM извлекает 19 структурированных полей → JSON.',
      credit_engine: 'Атомарные транзакции с row lock — race condition невозможен',
      credit_engineLong: '6 тиеров (free → enterprise). Soft limits с овердрафтом для бизнеса. Idempotency keys. BYOK (Bring Your Own Key) для OpenRouter. Usage % в статусбаре.',
      tokenomics: 'Трекинг стоимости каждого LLM-запроса, бюджет-гейт',
      tokenomicsLong: 'Каждый LLM-запрос: model, input/output tokens, estimated cost → workspace_llm_usages. Дневной лимит $5. Алерт на 80%. Premium модели блокируются при превышении.',
      email_bridge: 'Двусторонний email-канал: IMAP poll → маршрутизация в проекты',
      email_bridgeLong: 'IMAP poll каждые 2 минуты. SMTP отправка приглашений и артефактов. Маршрутизация по In-Reply-To → subject tag → EmailChannel → User. Защита от auto-reply и bounce.',
      pdf_publisher: 'Публичные PDF-ссылки на артефакты с замороженным контентом',
      pdf_publisherLong: 'Генерация публичных ссылок (/pdf/:token). Контент замораживается на момент создания. Print-ready B4 формат. Watermark. Счётчик просмотров. Без логина.',
    },
    metrics: {
      coffeebot: '82 кофейных профиля сгенерировано',
      inkcloak: 'AUROC 0.9948 точность детекции',
      aicpo: '43 артефакта на базе Product DNA',
      toolsites: '199 страниц на 5 доменах',
      openclaw: '5 агентов, задеплоено на 2 машинах',
      rackcloud: '17 IaaS-сервисов, 400+ серверов, 10 стоек',
      diycalc: '30+ калькуляторов',
      fitcalc: '40+ калькуляторов',
      aicpo_platform: '43 артефакта, 16 систем',
      llm_runtime: '7 уровней fallback, 0 downtime',
      discovery: '3 раунда, кеш 90 дней',
      dual_brain: '5 триггеров, 0.5с → Claude',
      artifact_pipeline: '43 типа, 3 стадии',
      semantic_memory: '19 data points, vector search',
      health_monitor: '6 коннекторов, real-time',
      team_os: 'SAML + OIDC, 4 роли',
      self_evolving: 'авто-draft еженедельно',
      evolution: 'Feedback → AI → Backlog',
      research_corpus: 'cross-user, TTL 90д',
      pain_extractor: '4 мессенджера → 19 полей',
      credit_engine: '6 тиеров, row locks',
      tokenomics: '$5/день, алерт 80%',
      email_bridge: 'poll 2 мин, auto-routing',
      pdf_publisher: 'B4, watermark, public links',
    },
  },
  stack: {
    title: 'Стек за $15/мес — Роман Неверов',
    description: `Как я запускаю ${PRODUCT_COUNT} AI-продуктов на $15/мес инфраструктуры.`,
    heading: '## Стек за $15/мес',
    subtitle: `Всё, что нужно для ${PRODUCT_COUNT} AI-продуктов. Общая стоимость: $15/мес.`,
    headers: {
      service: 'Сервис',
      cost: 'Стоимость',
      what: 'Что делает',
      limit: 'Бесплатный лимит',
    },
    savedHeading: '## Сэкономлено',
    savedSubtitle: 'Эквивалентные платные сервисы:',
    savedHeaders: {
      wouldPay: 'Платил бы за',
      cost: 'Стоимость',
      using: 'Использую вместо',
    },
    totalSavings: 'Ежемесячная экономия',
  },
  about: {
    title: 'Обо мне — Роман Неверов',
    description: 'AI Product Builder. 10+ лет в продуктовом управлении. 24 AI-продукта на $15/мес.',
    heading: '## Обо мне',
    bio1: 'Роман Неверов. Москва. AI Product Builder.',
    bio2: '<strong>10+ лет</strong> в продуктовом управлении. Последние 2 года — строю AI-продукты full-stack: от fine-tuning нейросетей до GPU-деплоя.',
    bio3: '<strong>Product Lead, PUNKT E</strong> (2024-2026) — самое популярное B2C EV-приложение в России (95K пользователей). Revenue: 70M → 396M₽ (×5.7) при падении рынка на 37%. NPS: 3.2 → 4.9. AI-продукты: предсказание завершения сессий (PyTorch), чатбот L1 (LLM), AI-исследование рынка.',
    bio4: '<strong>Head of Products, Mafin</strong> (2022-2024) — Top-3 insurtech. 11 продуктовых команд, 150 человек. P&L 4 бизнес-линий. Расширил линейку с 3 до 16 продуктов. M&A интеграция.',
    bio5: '<strong>Сейчас:</strong> 24 AI-продукта в продакшене на инфре $15/мес. Factory OS — оркестрация AI-агентов (Claude Opus, 15 ролей). LoRA fine-tuning DeBERTa (AUROC 0.9948). Full-stack: Rails, Python, PyTorch.',
    linksHeading: '## Ссылки',
    resumeLabel: 'Резюме (PDF)',
    emailLabel: 'Для предложений',
    tgLabel: 'Telegram',
    githubLabel: 'GitHub',
    nowHeading: '## Сейчас',
    now1: 'Открыт к предложениям: руководитель AI-продукта (500K+₽/мес)',
    now2: 'Развиваю AI CPO — платформу для продуктовых исследований',
    now3: 'Запускаю InkCloak — детектор AI-текста на fine-tuned DeBERTa',
  },
  contact: {
    title: 'Контакты — Роман Неверов',
    description: 'Открыт к предложениям и сотрудничеству. Email, Telegram, hh.ru.',
    heading: '## Контакты',
    subtitle: 'Открыт к предложениям и сотрудничеству',
    offersHeading: '## Чем могу быть полезен',
    offer1: 'Руководитель AI-продукта — полный цикл от стратегии до деплоя',
    offer2: 'AI-консалтинг — аудит продукта, построение AI-пайплайнов',
    offer3: 'Разработка AI-продуктов — от MVP до продакшена за недели',
  },
  newsletter: {
    title: 'Рассылка — Роман Неверов',
    description: 'Следите за проектами. Одно письмо когда выходит новый продукт.',
    heading: '## Рассылка',
    followBuild: 'Следите за проектами',
    followDesc: 'Одно письмо когда выходит новый продукт, важное обновление или статья. Без спама, без growth-хаков.',
    unsubscribe: 'Отписаться можно в любой момент.',
    formTitle: 'Следите за проектами',
    formSubtitle: 'Одно письмо когда выходит новый продукт. Без спама.',
    placeholder: 'ваш@email.ru',
    button: 'Подписаться',
    success: 'Подписка оформлена! Проверьте почту.',
    previousTopics: 'Предыдущие темы:',
    topic1: '> Как я построил 24 продукта за месяц',
    topic2: '> Стек за $15/мес',
    topic3: '> Factory OS: фабрика AI-агентов',
  },
  footer: {
    built: 'Роман Неверов',
    based: 'Москва',
  },
  blog: {
    title: 'Блог — Роман Неверов',
    subtitle: 'Строю в открытую. AI-продукты, стек, карьера.',
    backToBlog: 'Назад в блог',
    readMore: 'Читать',
    minRead: 'мин чтения',
  },
  common: {
    live: 'LIVE',
    launching: 'ЗАПУСК',
    building: 'В РАБОТЕ',
    planned: 'ПЛАН',
    built: 'ГОТОВО',
  },
};

export default t;
